// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for FlagStatus.
const (
	FlagStatusActioned  FlagStatus = "actioned"
	FlagStatusDismissed FlagStatus = "dismissed"
	FlagStatusPending   FlagStatus = "pending"
	FlagStatusReviewed  FlagStatus = "reviewed"
)

// Defines values for FlagTargetType.
const (
	FlagTargetTypeAlbum FlagTargetType = "album"
	FlagTargetTypeSong  FlagTargetType = "song"
)

// Defines values for PostFlagsJSONBodyTargetType.
const (
	PostFlagsJSONBodyTargetTypeAlbum PostFlagsJSONBodyTargetType = "album"
	PostFlagsJSONBodyTargetTypeSong  PostFlagsJSONBodyTargetType = "song"
)

// Defines values for PostFlagsFlagsIdReviewJSONBodyStatus.
const (
	PostFlagsFlagsIdReviewJSONBodyStatusActioned  PostFlagsFlagsIdReviewJSONBodyStatus = "actioned"
	PostFlagsFlagsIdReviewJSONBodyStatusDismissed PostFlagsFlagsIdReviewJSONBodyStatus = "dismissed"
	PostFlagsFlagsIdReviewJSONBodyStatusPending   PostFlagsFlagsIdReviewJSONBodyStatus = "pending"
	PostFlagsFlagsIdReviewJSONBodyStatusReviewed  PostFlagsFlagsIdReviewJSONBodyStatus = "reviewed"
)

// Defines values for GetSearchAlbumsParamsSort.
const (
	GetSearchAlbumsParamsSortPopularity  GetSearchAlbumsParamsSort = "popularity"
	GetSearchAlbumsParamsSortPrice       GetSearchAlbumsParamsSort = "price"
	GetSearchAlbumsParamsSortReleaseDate GetSearchAlbumsParamsSort = "release_date"
	GetSearchAlbumsParamsSortTitle       GetSearchAlbumsParamsSort = "title"
)

// Defines values for GetSearchArtistsParamsSort.
const (
	GetSearchArtistsParamsSortListeners  GetSearchArtistsParamsSort = "listeners"
	GetSearchArtistsParamsSortName       GetSearchArtistsParamsSort = "name"
	GetSearchArtistsParamsSortPopularity GetSearchArtistsParamsSort = "popularity"
)

// Defines values for GetSearchGenresParamsSort.
const (
	GetSearchGenresParamsSortName       GetSearchGenresParamsSort = "name"
	GetSearchGenresParamsSortPopularity GetSearchGenresParamsSort = "popularity"
)

// Defines values for GetSearchPlaylistsParamsSort.
const (
	GetSearchPlaylistsParamsSortCreatedAt  GetSearchPlaylistsParamsSort = "created_at"
	GetSearchPlaylistsParamsSortPopularity GetSearchPlaylistsParamsSort = "popularity"
	GetSearchPlaylistsParamsSortTitle      GetSearchPlaylistsParamsSort = "title"
	GetSearchPlaylistsParamsSortUpdatedAt  GetSearchPlaylistsParamsSort = "updated_at"
)

// Defines values for GetSearchSongsParamsSort.
const (
	Duration    GetSearchSongsParamsSort = "duration"
	Popularity  GetSearchSongsParamsSort = "popularity"
	ReleaseDate GetSearchSongsParamsSort = "release_date"
	Title       GetSearchSongsParamsSort = "title"
)

// Defines values for GetSearchSongsParamsOrder.
const (
	Asc  GetSearchSongsParamsOrder = "asc"
	Desc GetSearchSongsParamsOrder = "desc"
)

// Album defines model for Album.
type Album struct {
	ArtistId      openapi_types.UUID  `json:"artistId"`
	CoverImageUrl *string             `json:"coverImageUrl,omitempty"`
	CreatedAt     *time.Time          `json:"createdAt,omitempty"`
	Description   *string             `json:"description,omitempty"`
	Id            *openapi_types.UUID `json:"id,omitempty"`
	IsFlagged     *bool               `json:"is_flagged,omitempty"`
	Likes         *float32            `json:"likes,omitempty"`
	Price         *int                `json:"price,omitempty"`
	ReleaseDate   *time.Time          `json:"releaseDate,omitempty"`
	Title         string              `json:"title"`
	UpdatedAt     *time.Time          `json:"updatedAt,omitempty"`
}

// Artist defines model for Artist.
type Artist struct {
	ArtistName       string              `json:"artistName"`
	CreatedAt        *time.Time          `json:"createdAt,omitempty"`
	Id               *openapi_types.UUID `json:"id,omitempty"`
	MonthlyListeners *int                `json:"monthlyListeners,omitempty"`
	UpdatedAt        *time.Time          `json:"updatedAt,omitempty"`
	UserId           openapi_types.UUID  `json:"userId"`
	Verified         *bool               `json:"verified,omitempty"`
	WalletBalance    *int                `json:"walletBalance,omitempty"`
}

// Contributor defines model for Contributor.
type Contributor struct {
	ArtistId          openapi_types.UUID `json:"artistId"`
	ContributionType  string             `json:"contributionType"`
	CreatedAt         *time.Time         `json:"createdAt,omitempty"`
	RoyaltyPercentage *int               `json:"royaltyPercentage,omitempty"`
	UpdatedAt         *time.Time         `json:"updatedAt,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Code    int     `json:"code"`
	Details *string `json:"details,omitempty"`
	Message string  `json:"message"`
}

// Flag defines model for Flag.
type Flag struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Description Detailed explanation of the flag
	Description *string `json:"description,omitempty"`

	// Id Auto-generated unique identifier
	Id *openapi_types.UUID `json:"id,omitempty"`

	// Reason Category of the violation
	Reason string `json:"reason"`

	// ReporterUserId ID of the user reporting the content
	ReporterUserId openapi_types.UUID `json:"reporter_user_id"`

	// Status Current status of the flag
	Status FlagStatus `json:"status"`

	// TargetId ID of the flagged content (song or album)
	TargetId openapi_types.UUID `json:"target_id"`

	// TargetType Type of content being flagged
	TargetType FlagTargetType `json:"target_type"`
	UpdatedAt  *time.Time     `json:"updated_at,omitempty"`
}

// FlagStatus Current status of the flag
type FlagStatus string

// FlagTargetType Type of content being flagged
type FlagTargetType string

// Genre defines model for Genre.
type Genre struct {
	Description string              `json:"description"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	ImageUrl    *string             `json:"imageUrl,omitempty"`
	Name        string              `json:"name"`
}

// Playlist defines model for Playlist.
type Playlist struct {
	CoverImageUrl *string             `json:"coverImageUrl,omitempty"`
	CreatedAt     *time.Time          `json:"createdAt,omitempty"`
	Description   *string             `json:"description,omitempty"`
	Id            *openapi_types.UUID `json:"id,omitempty"`
	IsPublic      *bool               `json:"isPublic,omitempty"`
	Title         string              `json:"title"`
	UpdatedAt     *time.Time          `json:"updatedAt,omitempty"`
	UserId        openapi_types.UUID  `json:"userId"`
}

// Purchase defines model for Purchase.
type Purchase struct {
	Currency      string              `json:"currency"`
	Id            *openapi_types.UUID `json:"id,omitempty"`
	PaymentStatus string              `json:"paymentStatus"`
	PurchasePrice int                 `json:"purchasePrice"`
	PurchasedAt   *time.Time          `json:"purchasedAt,omitempty"`
	UserId        openapi_types.UUID  `json:"userId"`
}

// Song defines model for Song.
type Song struct {
	AlbumId       *openapi_types.UUID `json:"albumId,omitempty"`
	ArtistId      openapi_types.UUID  `json:"artistId"`
	ArtistsNames  []string            `json:"artists_names"`
	AudioUrl      string              `json:"audioUrl"`
	CoverImageUrl *string             `json:"coverImageUrl,omitempty"`
	CreatedAt     *time.Time          `json:"createdAt,omitempty"`

	// Duration Duration in seconds
	Duration    int                 `json:"duration"`
	GenreId     openapi_types.UUID  `json:"genreId"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	IsFlagged   *bool               `json:"is_flagged,omitempty"`
	PlaysCount  *int                `json:"playsCount,omitempty"`
	PreviewUrl  *string             `json:"previewUrl,omitempty"`
	Price       int                 `json:"price"`
	ReleaseDate time.Time           `json:"releaseDate"`
	Title       string              `json:"title"`
	UpdatedAt   *time.Time          `json:"updatedAt,omitempty"`
}

// User defines model for User.
type User struct {
	Bio             *string             `json:"bio,omitempty"`
	CreatedAt       *time.Time          `json:"createdAt,omitempty"`
	Email           openapi_types.Email `json:"email"`
	FirstName       string              `json:"firstName"`
	Id              *openapi_types.UUID `json:"id,omitempty"`
	IsArtist        *bool               `json:"isArtist,omitempty"`
	LastName        string              `json:"lastName"`
	Password        *string             `json:"password,omitempty"`
	PhoneNumber     *string             `json:"phoneNumber,omitempty"`
	ProfileImageUrl *string             `json:"profileImageUrl,omitempty"`
	UpdatedAt       *time.Time          `json:"updatedAt,omitempty"`
	Username        string              `json:"username"`
}

// AlbumId defines model for albumId.
type AlbumId = openapi_types.UUID

// ArtistId defines model for artistId.
type ArtistId = openapi_types.UUID

// FlagsId defines model for flagsId.
type FlagsId = openapi_types.UUID

// GenreId defines model for genreId.
type GenreId = openapi_types.UUID

// Limit defines model for limit.
type Limit = int

// Page defines model for page.
type Page = int

// PlaylistId defines model for playlistId.
type PlaylistId = openapi_types.UUID

// SongId defines model for songId.
type SongId = openapi_types.UUID

// UserId defines model for userId.
type UserId = openapi_types.UUID

// GetAlbumsParams defines parameters for GetAlbums.
type GetAlbumsParams struct {
	// Page Page integer
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of items per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Artist Filter by artist ID
	Artist *openapi_types.UUID `form:"artist,omitempty" json:"artist,omitempty"`
}

// GetArtistsParams defines parameters for GetArtists.
type GetArtistsParams struct {
	// Page Page integer
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of items per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Verified Filter by verified status
	Verified *bool `form:"verified,omitempty" json:"verified,omitempty"`
}

// GetArtistsArtistIdSongsParams defines parameters for GetArtistsArtistIdSongs.
type GetArtistsArtistIdSongsParams struct {
	// Page Page integer
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of items per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostCreateAdminJSONBody defines parameters for PostCreateAdmin.
type PostCreateAdminJSONBody struct {
	UserId *openapi_types.UUID `json:"userId,omitempty"`
}

// PostFlagsJSONBody defines parameters for PostFlags.
type PostFlagsJSONBody struct {
	Description *string                     `json:"description,omitempty"`
	Reason      string                      `json:"reason"`
	TargetId    openapi_types.UUID          `json:"targetId"`
	TargetType  PostFlagsJSONBodyTargetType `json:"targetType"`
}

// PostFlagsJSONBodyTargetType defines parameters for PostFlags.
type PostFlagsJSONBodyTargetType string

// PostFlagsFlagsIdReviewJSONBody defines parameters for PostFlagsFlagsIdReview.
type PostFlagsFlagsIdReviewJSONBody struct {
	Status *PostFlagsFlagsIdReviewJSONBodyStatus `json:"status,omitempty"`
}

// PostFlagsFlagsIdReviewJSONBodyStatus defines parameters for PostFlagsFlagsIdReview.
type PostFlagsFlagsIdReviewJSONBodyStatus string

// PostLoginJSONBody defines parameters for PostLogin.
type PostLoginJSONBody struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// PostPlaylistsPlaylistIdSongsJSONBody defines parameters for PostPlaylistsPlaylistIdSongs.
type PostPlaylistsPlaylistIdSongsJSONBody struct {
	SongId openapi_types.UUID `json:"songId"`
}

// PostPurchasesAlbumsJSONBody defines parameters for PostPurchasesAlbums.
type PostPurchasesAlbumsJSONBody struct {
	AlbumId         openapi_types.UUID `json:"albumId"`
	PaymentMethodId string             `json:"paymentMethodId"`
	UserId          openapi_types.UUID `json:"userId"`
}

// PostPurchasesSongsJSONBody defines parameters for PostPurchasesSongs.
type PostPurchasesSongsJSONBody struct {
	// PaymentMethodId Stripe payment method ID
	PaymentMethodId string             `json:"paymentMethodId"`
	SongId          openapi_types.UUID `json:"songId"`
	UserId          openapi_types.UUID `json:"userId"`
}

// GetSearchParams defines parameters for GetSearch.
type GetSearchParams struct {
	// Query Search term
	Query string `form:"query" json:"query"`

	// Types Comma-separated list of content types to search (songs,albums,artists,playlists,genres)
	Types *string `form:"types,omitempty" json:"types,omitempty"`

	// Page Page integer
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of items per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetSearchAlbumsParams defines parameters for GetSearchAlbums.
type GetSearchAlbumsParams struct {
	// Query Search term (album title)
	Query *string `form:"query,omitempty" json:"query,omitempty"`

	// Artist Filter by artist name or ID
	Artist *string `form:"artist,omitempty" json:"artist,omitempty"`

	// Genre Filter by genre name or ID
	Genre *string `form:"genre,omitempty" json:"genre,omitempty"`

	// Sort Sort field (popularity,release_date,price)
	Sort *GetSearchAlbumsParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Page Page integer
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of items per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetSearchAlbumsParamsSort defines parameters for GetSearchAlbums.
type GetSearchAlbumsParamsSort string

// GetSearchArtistsParams defines parameters for GetSearchArtists.
type GetSearchArtistsParams struct {
	// Query Search term (artist name)
	Query *string `form:"query,omitempty" json:"query,omitempty"`

	// Genre Filter by genre name or ID
	Genre *string `form:"genre,omitempty" json:"genre,omitempty"`

	// Sort Sort field (popularity,listeners,name)
	Sort *GetSearchArtistsParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Page Page integer
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of items per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetSearchArtistsParamsSort defines parameters for GetSearchArtists.
type GetSearchArtistsParamsSort string

// GetSearchGenresParams defines parameters for GetSearchGenres.
type GetSearchGenresParams struct {
	// Query Search term (genre name)
	Query *string `form:"query,omitempty" json:"query,omitempty"`

	// Sort Sort field (popularity,name)
	Sort *GetSearchGenresParamsSort `form:"sort,omitempty" json:"sort,omitempty"`
}

// GetSearchGenresParamsSort defines parameters for GetSearchGenres.
type GetSearchGenresParamsSort string

// GetSearchPlaylistsParams defines parameters for GetSearchPlaylists.
type GetSearchPlaylistsParams struct {
	// Query Search term (playlist title or description)
	Query *string `form:"query,omitempty" json:"query,omitempty"`

	// Owner Filter by owner username or ID
	Owner *string `form:"owner,omitempty" json:"owner,omitempty"`

	// IsPublic Filter by public/private status
	IsPublic *bool `form:"isPublic,omitempty" json:"isPublic,omitempty"`

	// Sort Sort field (popularity,created_at,updated_at)
	Sort *GetSearchPlaylistsParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Page Page integer
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of items per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetSearchPlaylistsParamsSort defines parameters for GetSearchPlaylists.
type GetSearchPlaylistsParamsSort string

// GetSearchSongsParams defines parameters for GetSearchSongs.
type GetSearchSongsParams struct {
	// Query Search term (title or lyrics)
	Query *string `form:"query,omitempty" json:"query,omitempty"`

	// Artist Filter by artist name or ID
	Artist *string `form:"artist,omitempty" json:"artist,omitempty"`

	// Genre Filter by genre name or ID
	Genre *string `form:"genre,omitempty" json:"genre,omitempty"`

	// Sort Sort field (popularity,release_date,duration)
	Sort *GetSearchSongsParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Order Sort order
	Order *GetSearchSongsParamsOrder `form:"order,omitempty" json:"order,omitempty"`

	// Page Page integer
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of items per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetSearchSongsParamsSort defines parameters for GetSearchSongs.
type GetSearchSongsParamsSort string

// GetSearchSongsParamsOrder defines parameters for GetSearchSongs.
type GetSearchSongsParamsOrder string

// GetSongsParams defines parameters for GetSongs.
type GetSongsParams struct {
	// Page Page integer
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of items per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Genre Filter by genre ID
	Genre *string `form:"genre,omitempty" json:"genre,omitempty"`

	// Artist Filter by artist ID
	Artist *string `form:"artist,omitempty" json:"artist,omitempty"`

	// Album Filter by album ID
	Album *string `form:"album,omitempty" json:"album,omitempty"`
}

// PostStreamsJSONBody defines parameters for PostStreams.
type PostStreamsJSONBody struct {
	CountryCode *string            `json:"countryCode,omitempty"`
	DeviceType  *string            `json:"deviceType,omitempty"`
	IsPreview   *bool              `json:"isPreview,omitempty"`
	SongId      openapi_types.UUID `json:"songId"`
}

// PostTipsJSONBody defines parameters for PostTips.
type PostTipsJSONBody struct {
	Amount          int                `json:"amount"`
	ArtistId        openapi_types.UUID `json:"artistId"`
	Message         *string            `json:"message,omitempty"`
	PaymentMethodId string             `json:"paymentMethodId"`
}

// GetUsersParams defines parameters for GetUsers.
type GetUsersParams struct {
	// Page Page integer
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of items per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetUsersUserIdLibraryPurchasesParams defines parameters for GetUsersUserIdLibraryPurchases.
type GetUsersUserIdLibraryPurchasesParams struct {
	// Page Page integer
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of items per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetUsersUserIdRecentParams defines parameters for GetUsersUserIdRecent.
type GetUsersUserIdRecentParams struct {
	// Limit Number of items per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Page Page integer
	Page *Page `form:"page,omitempty" json:"page,omitempty"`
}

// PostAlbumsJSONRequestBody defines body for PostAlbums for application/json ContentType.
type PostAlbumsJSONRequestBody = Album

// PutAlbumsAlbumIdJSONRequestBody defines body for PutAlbumsAlbumId for application/json ContentType.
type PutAlbumsAlbumIdJSONRequestBody = Album

// PostAlbumsAlbumIdContributorsJSONRequestBody defines body for PostAlbumsAlbumIdContributors for application/json ContentType.
type PostAlbumsAlbumIdContributorsJSONRequestBody = Contributor

// PostArtistsJSONRequestBody defines body for PostArtists for application/json ContentType.
type PostArtistsJSONRequestBody = Artist

// PutArtistsArtistIdJSONRequestBody defines body for PutArtistsArtistId for application/json ContentType.
type PutArtistsArtistIdJSONRequestBody = Artist

// PostCreateAdminJSONRequestBody defines body for PostCreateAdmin for application/json ContentType.
type PostCreateAdminJSONRequestBody PostCreateAdminJSONBody

// PostFlagsJSONRequestBody defines body for PostFlags for application/json ContentType.
type PostFlagsJSONRequestBody PostFlagsJSONBody

// PostFlagsFlagsIdReviewJSONRequestBody defines body for PostFlagsFlagsIdReview for application/json ContentType.
type PostFlagsFlagsIdReviewJSONRequestBody PostFlagsFlagsIdReviewJSONBody

// PostGenresJSONRequestBody defines body for PostGenres for application/json ContentType.
type PostGenresJSONRequestBody = Genre

// PutGenresGenreIdJSONRequestBody defines body for PutGenresGenreId for application/json ContentType.
type PutGenresGenreIdJSONRequestBody = Genre

// PostLoginJSONRequestBody defines body for PostLogin for application/json ContentType.
type PostLoginJSONRequestBody PostLoginJSONBody

// PutPlaylistsPlaylistIdJSONRequestBody defines body for PutPlaylistsPlaylistId for application/json ContentType.
type PutPlaylistsPlaylistIdJSONRequestBody = Playlist

// PostPlaylistsPlaylistIdSongsJSONRequestBody defines body for PostPlaylistsPlaylistIdSongs for application/json ContentType.
type PostPlaylistsPlaylistIdSongsJSONRequestBody PostPlaylistsPlaylistIdSongsJSONBody

// PostPurchasesAlbumsJSONRequestBody defines body for PostPurchasesAlbums for application/json ContentType.
type PostPurchasesAlbumsJSONRequestBody PostPurchasesAlbumsJSONBody

// PostPurchasesSongsJSONRequestBody defines body for PostPurchasesSongs for application/json ContentType.
type PostPurchasesSongsJSONRequestBody PostPurchasesSongsJSONBody

// PostSongsJSONRequestBody defines body for PostSongs for application/json ContentType.
type PostSongsJSONRequestBody = Song

// PutSongsSongIdJSONRequestBody defines body for PutSongsSongId for application/json ContentType.
type PutSongsSongIdJSONRequestBody = Song

// PostSongsSongIdContributorsJSONRequestBody defines body for PostSongsSongIdContributors for application/json ContentType.
type PostSongsSongIdContributorsJSONRequestBody = Contributor

// PostStreamsJSONRequestBody defines body for PostStreams for application/json ContentType.
type PostStreamsJSONRequestBody PostStreamsJSONBody

// PostTipsJSONRequestBody defines body for PostTips for application/json ContentType.
type PostTipsJSONRequestBody PostTipsJSONBody

// PostUsersJSONRequestBody defines body for PostUsers for application/json ContentType.
type PostUsersJSONRequestBody = User

// PutUsersUserIdJSONRequestBody defines body for PutUsersUserId for application/json ContentType.
type PutUsersUserIdJSONRequestBody = User

// PostUsersUserIdPlaylistsJSONRequestBody defines body for PostUsersUserIdPlaylists for application/json ContentType.
type PostUsersUserIdPlaylistsJSONRequestBody = Playlist

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all albums
	// (GET /albums)
	GetAlbums(c *fiber.Ctx, params GetAlbumsParams) error
	// Create a new album
	// (POST /albums)
	PostAlbums(c *fiber.Ctx) error
	// Delete album
	// (DELETE /albums/{albumId})
	DeleteAlbumsAlbumId(c *fiber.Ctx, albumId AlbumId) error
	// Get album by ID
	// (GET /albums/{albumId})
	GetAlbumsAlbumId(c *fiber.Ctx, albumId AlbumId) error
	// Update album
	// (PUT /albums/{albumId})
	PutAlbumsAlbumId(c *fiber.Ctx, albumId AlbumId) error
	// Get album contributors
	// (GET /albums/{albumId}/contributors)
	GetAlbumsAlbumIdContributors(c *fiber.Ctx, albumId AlbumId) error
	// Add contributor to album
	// (POST /albums/{albumId}/contributors)
	PostAlbumsAlbumIdContributors(c *fiber.Ctx, albumId AlbumId) error
	// Get album's songs
	// (GET /albums/{albumId}/songs)
	GetAlbumsAlbumIdSongs(c *fiber.Ctx, albumId AlbumId) error
	// List all artists
	// (GET /artists)
	GetArtists(c *fiber.Ctx, params GetArtistsParams) error
	// Create a new artist profile
	// (POST /artists)
	PostArtists(c *fiber.Ctx) error
	// Get artist by ID
	// (GET /artists/{artistId})
	GetArtistsArtistId(c *fiber.Ctx, artistId ArtistId) error
	// Update artist
	// (PUT /artists/{artistId})
	PutArtistsArtistId(c *fiber.Ctx, artistId ArtistId) error
	// Get artist's songs
	// (GET /artists/{artistId}/songs)
	GetArtistsArtistIdSongs(c *fiber.Ctx, artistId ArtistId, params GetArtistsArtistIdSongsParams) error
	// Create An admin
	// (POST /createAdmin)
	PostCreateAdmin(c *fiber.Ctx) error
	// Flag content
	// (GET /flags)
	GetFlags(c *fiber.Ctx) error
	// Flag content
	// (POST /flags)
	PostFlags(c *fiber.Ctx) error
	// Get flagged content
	// (GET /flags/{flagsId})
	GetFlagsFlagsId(c *fiber.Ctx, flagsId FlagsId) error
	// Review a flagged content
	// (POST /flags/{flagsId}/review)
	PostFlagsFlagsIdReview(c *fiber.Ctx, flagsId FlagsId) error
	// Flag content
	// (POST /flags/{songId})
	PostFlagsSongId(c *fiber.Ctx, songId SongId) error
	// List all genres
	// (GET /genres)
	GetGenres(c *fiber.Ctx) error
	// Create a genre
	// (POST /genres)
	PostGenres(c *fiber.Ctx) error
	// Get genre by ID
	// (GET /genres/{genreId})
	GetGenresGenreId(c *fiber.Ctx, genreId GenreId) error
	// Update a genre
	// (PUT /genres/{genreId})
	PutGenresGenreId(c *fiber.Ctx, genreId GenreId) error
	// User login credentials
	// (POST /login)
	PostLogin(c *fiber.Ctx) error
	// Delete playlist
	// (DELETE /playlists/{playlistId})
	DeletePlaylistsPlaylistId(c *fiber.Ctx, playlistId PlaylistId) error
	// Get playlist by ID
	// (GET /playlists/{playlistId})
	GetPlaylistsPlaylistId(c *fiber.Ctx, playlistId PlaylistId) error
	// Update playlist
	// (PUT /playlists/{playlistId})
	PutPlaylistsPlaylistId(c *fiber.Ctx, playlistId PlaylistId) error
	// Get playlist songs
	// (GET /playlists/{playlistId}/songs)
	GetPlaylistsPlaylistIdSongs(c *fiber.Ctx, playlistId PlaylistId) error
	// Add song to playlist
	// (POST /playlists/{playlistId}/songs)
	PostPlaylistsPlaylistIdSongs(c *fiber.Ctx, playlistId PlaylistId) error
	// Remove song from playlist
	// (DELETE /playlists/{playlistId}/songs/{songId})
	DeletePlaylistsPlaylistIdSongsSongId(c *fiber.Ctx, playlistId PlaylistId, songId SongId) error
	// Purchase an album
	// (POST /purchases/albums)
	PostPurchasesAlbums(c *fiber.Ctx) error
	// Purchase a song
	// (POST /purchases/songs)
	PostPurchasesSongs(c *fiber.Ctx) error
	// Global search across all content types
	// (GET /search)
	GetSearch(c *fiber.Ctx, params GetSearchParams) error
	// Search albums with advanced filters
	// (GET /search/albums)
	GetSearchAlbums(c *fiber.Ctx, params GetSearchAlbumsParams) error
	// Search artists with advanced filters
	// (GET /search/artists)
	GetSearchArtists(c *fiber.Ctx, params GetSearchArtistsParams) error
	// Search genres
	// (GET /search/genres)
	GetSearchGenres(c *fiber.Ctx, params GetSearchGenresParams) error
	// Search playlists
	// (GET /search/playlists)
	GetSearchPlaylists(c *fiber.Ctx, params GetSearchPlaylistsParams) error
	// Search songs with advanced filters
	// (GET /search/songs)
	GetSearchSongs(c *fiber.Ctx, params GetSearchSongsParams) error
	// List all songs
	// (GET /songs)
	GetSongs(c *fiber.Ctx, params GetSongsParams) error
	// Create a new song
	// (POST /songs)
	PostSongs(c *fiber.Ctx) error
	// Delete song
	// (DELETE /songs/{songId})
	DeleteSongsSongId(c *fiber.Ctx, songId SongId) error
	// Get song by ID
	// (GET /songs/{songId})
	GetSongsSongId(c *fiber.Ctx, songId SongId) error
	// Update song
	// (PUT /songs/{songId})
	PutSongsSongId(c *fiber.Ctx, songId SongId) error
	// Get song contributors
	// (GET /songs/{songId}/contributors)
	GetSongsSongIdContributors(c *fiber.Ctx, songId SongId) error
	// Add contributor to song
	// (POST /songs/{songId}/contributors)
	PostSongsSongIdContributors(c *fiber.Ctx, songId SongId) error
	// Record a stream
	// (POST /streams)
	PostStreams(c *fiber.Ctx) error
	// Send tip to artist
	// (POST /tips)
	PostTips(c *fiber.Ctx) error
	// List all users
	// (GET /users)
	GetUsers(c *fiber.Ctx, params GetUsersParams) error
	// Create a new user
	// (POST /users)
	PostUsers(c *fiber.Ctx) error
	// Delete user
	// (DELETE /users/{userId})
	DeleteUsersUserId(c *fiber.Ctx, userId UserId) error
	// Get user by ID
	// (GET /users/{userId})
	GetUsersUserId(c *fiber.Ctx, userId UserId) error
	// Update user
	// (PUT /users/{userId})
	PutUsersUserId(c *fiber.Ctx, userId UserId) error
	// Get user's purchased albums
	// (GET /users/{userId}/library/albums)
	GetUsersUserIdLibraryAlbums(c *fiber.Ctx, userId UserId) error
	// Get user's purchase history
	// (GET /users/{userId}/library/purchases)
	GetUsersUserIdLibraryPurchases(c *fiber.Ctx, userId UserId, params GetUsersUserIdLibraryPurchasesParams) error
	// Get user's purchased songs
	// (GET /users/{userId}/library/songs)
	GetUsersUserIdLibrarySongs(c *fiber.Ctx, userId UserId) error
	// Get user's playlists
	// (GET /users/{userId}/playlists)
	GetUsersUserIdPlaylists(c *fiber.Ctx, userId UserId) error
	// Create a new playlist
	// (POST /users/{userId}/playlists)
	PostUsersUserIdPlaylists(c *fiber.Ctx, userId UserId) error
	// Get recently played music
	// (GET /users/{userId}/recent)
	GetUsersUserIdRecent(c *fiber.Ctx, userId UserId, params GetUsersUserIdRecentParams) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// GetAlbums operation middleware
func (siw *ServerInterfaceWrapper) GetAlbums(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAlbumsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", query, &params.Page)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter page: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "artist" -------------

	err = runtime.BindQueryParameter("form", true, false, "artist", query, &params.Artist)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter artist: %w", err).Error())
	}

	return siw.Handler.GetAlbums(c, params)
}

// PostAlbums operation middleware
func (siw *ServerInterfaceWrapper) PostAlbums(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostAlbums(c)
}

// DeleteAlbumsAlbumId operation middleware
func (siw *ServerInterfaceWrapper) DeleteAlbumsAlbumId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "albumId" -------------
	var albumId AlbumId

	err = runtime.BindStyledParameter("simple", false, "albumId", c.Params("albumId"), &albumId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter albumId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.DeleteAlbumsAlbumId(c, albumId)
}

// GetAlbumsAlbumId operation middleware
func (siw *ServerInterfaceWrapper) GetAlbumsAlbumId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "albumId" -------------
	var albumId AlbumId

	err = runtime.BindStyledParameter("simple", false, "albumId", c.Params("albumId"), &albumId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter albumId: %w", err).Error())
	}

	return siw.Handler.GetAlbumsAlbumId(c, albumId)
}

// PutAlbumsAlbumId operation middleware
func (siw *ServerInterfaceWrapper) PutAlbumsAlbumId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "albumId" -------------
	var albumId AlbumId

	err = runtime.BindStyledParameter("simple", false, "albumId", c.Params("albumId"), &albumId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter albumId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PutAlbumsAlbumId(c, albumId)
}

// GetAlbumsAlbumIdContributors operation middleware
func (siw *ServerInterfaceWrapper) GetAlbumsAlbumIdContributors(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "albumId" -------------
	var albumId AlbumId

	err = runtime.BindStyledParameter("simple", false, "albumId", c.Params("albumId"), &albumId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter albumId: %w", err).Error())
	}

	return siw.Handler.GetAlbumsAlbumIdContributors(c, albumId)
}

// PostAlbumsAlbumIdContributors operation middleware
func (siw *ServerInterfaceWrapper) PostAlbumsAlbumIdContributors(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "albumId" -------------
	var albumId AlbumId

	err = runtime.BindStyledParameter("simple", false, "albumId", c.Params("albumId"), &albumId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter albumId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostAlbumsAlbumIdContributors(c, albumId)
}

// GetAlbumsAlbumIdSongs operation middleware
func (siw *ServerInterfaceWrapper) GetAlbumsAlbumIdSongs(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "albumId" -------------
	var albumId AlbumId

	err = runtime.BindStyledParameter("simple", false, "albumId", c.Params("albumId"), &albumId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter albumId: %w", err).Error())
	}

	return siw.Handler.GetAlbumsAlbumIdSongs(c, albumId)
}

// GetArtists operation middleware
func (siw *ServerInterfaceWrapper) GetArtists(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetArtistsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", query, &params.Page)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter page: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "verified" -------------

	err = runtime.BindQueryParameter("form", true, false, "verified", query, &params.Verified)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter verified: %w", err).Error())
	}

	return siw.Handler.GetArtists(c, params)
}

// PostArtists operation middleware
func (siw *ServerInterfaceWrapper) PostArtists(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostArtists(c)
}

// GetArtistsArtistId operation middleware
func (siw *ServerInterfaceWrapper) GetArtistsArtistId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "artistId" -------------
	var artistId ArtistId

	err = runtime.BindStyledParameter("simple", false, "artistId", c.Params("artistId"), &artistId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter artistId: %w", err).Error())
	}

	return siw.Handler.GetArtistsArtistId(c, artistId)
}

// PutArtistsArtistId operation middleware
func (siw *ServerInterfaceWrapper) PutArtistsArtistId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "artistId" -------------
	var artistId ArtistId

	err = runtime.BindStyledParameter("simple", false, "artistId", c.Params("artistId"), &artistId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter artistId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PutArtistsArtistId(c, artistId)
}

// GetArtistsArtistIdSongs operation middleware
func (siw *ServerInterfaceWrapper) GetArtistsArtistIdSongs(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "artistId" -------------
	var artistId ArtistId

	err = runtime.BindStyledParameter("simple", false, "artistId", c.Params("artistId"), &artistId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter artistId: %w", err).Error())
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetArtistsArtistIdSongsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", query, &params.Page)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter page: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	return siw.Handler.GetArtistsArtistIdSongs(c, artistId, params)
}

// PostCreateAdmin operation middleware
func (siw *ServerInterfaceWrapper) PostCreateAdmin(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostCreateAdmin(c)
}

// GetFlags operation middleware
func (siw *ServerInterfaceWrapper) GetFlags(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetFlags(c)
}

// PostFlags operation middleware
func (siw *ServerInterfaceWrapper) PostFlags(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostFlags(c)
}

// GetFlagsFlagsId operation middleware
func (siw *ServerInterfaceWrapper) GetFlagsFlagsId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "flagsId" -------------
	var flagsId FlagsId

	err = runtime.BindStyledParameter("simple", false, "flagsId", c.Params("flagsId"), &flagsId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter flagsId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetFlagsFlagsId(c, flagsId)
}

// PostFlagsFlagsIdReview operation middleware
func (siw *ServerInterfaceWrapper) PostFlagsFlagsIdReview(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "flagsId" -------------
	var flagsId FlagsId

	err = runtime.BindStyledParameter("simple", false, "flagsId", c.Params("flagsId"), &flagsId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter flagsId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostFlagsFlagsIdReview(c, flagsId)
}

// PostFlagsSongId operation middleware
func (siw *ServerInterfaceWrapper) PostFlagsSongId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "songId" -------------
	var songId SongId

	err = runtime.BindStyledParameter("simple", false, "songId", c.Params("songId"), &songId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter songId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostFlagsSongId(c, songId)
}

// GetGenres operation middleware
func (siw *ServerInterfaceWrapper) GetGenres(c *fiber.Ctx) error {

	return siw.Handler.GetGenres(c)
}

// PostGenres operation middleware
func (siw *ServerInterfaceWrapper) PostGenres(c *fiber.Ctx) error {

	return siw.Handler.PostGenres(c)
}

// GetGenresGenreId operation middleware
func (siw *ServerInterfaceWrapper) GetGenresGenreId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "genreId" -------------
	var genreId GenreId

	err = runtime.BindStyledParameter("simple", false, "genreId", c.Params("genreId"), &genreId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter genreId: %w", err).Error())
	}

	return siw.Handler.GetGenresGenreId(c, genreId)
}

// PutGenresGenreId operation middleware
func (siw *ServerInterfaceWrapper) PutGenresGenreId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "genreId" -------------
	var genreId GenreId

	err = runtime.BindStyledParameter("simple", false, "genreId", c.Params("genreId"), &genreId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter genreId: %w", err).Error())
	}

	return siw.Handler.PutGenresGenreId(c, genreId)
}

// PostLogin operation middleware
func (siw *ServerInterfaceWrapper) PostLogin(c *fiber.Ctx) error {

	return siw.Handler.PostLogin(c)
}

// DeletePlaylistsPlaylistId operation middleware
func (siw *ServerInterfaceWrapper) DeletePlaylistsPlaylistId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "playlistId" -------------
	var playlistId PlaylistId

	err = runtime.BindStyledParameter("simple", false, "playlistId", c.Params("playlistId"), &playlistId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter playlistId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.DeletePlaylistsPlaylistId(c, playlistId)
}

// GetPlaylistsPlaylistId operation middleware
func (siw *ServerInterfaceWrapper) GetPlaylistsPlaylistId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "playlistId" -------------
	var playlistId PlaylistId

	err = runtime.BindStyledParameter("simple", false, "playlistId", c.Params("playlistId"), &playlistId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter playlistId: %w", err).Error())
	}

	return siw.Handler.GetPlaylistsPlaylistId(c, playlistId)
}

// PutPlaylistsPlaylistId operation middleware
func (siw *ServerInterfaceWrapper) PutPlaylistsPlaylistId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "playlistId" -------------
	var playlistId PlaylistId

	err = runtime.BindStyledParameter("simple", false, "playlistId", c.Params("playlistId"), &playlistId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter playlistId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PutPlaylistsPlaylistId(c, playlistId)
}

// GetPlaylistsPlaylistIdSongs operation middleware
func (siw *ServerInterfaceWrapper) GetPlaylistsPlaylistIdSongs(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "playlistId" -------------
	var playlistId PlaylistId

	err = runtime.BindStyledParameter("simple", false, "playlistId", c.Params("playlistId"), &playlistId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter playlistId: %w", err).Error())
	}

	return siw.Handler.GetPlaylistsPlaylistIdSongs(c, playlistId)
}

// PostPlaylistsPlaylistIdSongs operation middleware
func (siw *ServerInterfaceWrapper) PostPlaylistsPlaylistIdSongs(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "playlistId" -------------
	var playlistId PlaylistId

	err = runtime.BindStyledParameter("simple", false, "playlistId", c.Params("playlistId"), &playlistId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter playlistId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostPlaylistsPlaylistIdSongs(c, playlistId)
}

// DeletePlaylistsPlaylistIdSongsSongId operation middleware
func (siw *ServerInterfaceWrapper) DeletePlaylistsPlaylistIdSongsSongId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "playlistId" -------------
	var playlistId PlaylistId

	err = runtime.BindStyledParameter("simple", false, "playlistId", c.Params("playlistId"), &playlistId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter playlistId: %w", err).Error())
	}

	// ------------- Path parameter "songId" -------------
	var songId SongId

	err = runtime.BindStyledParameter("simple", false, "songId", c.Params("songId"), &songId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter songId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.DeletePlaylistsPlaylistIdSongsSongId(c, playlistId, songId)
}

// PostPurchasesAlbums operation middleware
func (siw *ServerInterfaceWrapper) PostPurchasesAlbums(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostPurchasesAlbums(c)
}

// PostPurchasesSongs operation middleware
func (siw *ServerInterfaceWrapper) PostPurchasesSongs(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostPurchasesSongs(c)
}

// GetSearch operation middleware
func (siw *ServerInterfaceWrapper) GetSearch(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSearchParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "query" -------------

	if paramValue := c.Query("query"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument query is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "query", query, &params.Query)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter query: %w", err).Error())
	}

	// ------------- Optional query parameter "types" -------------

	err = runtime.BindQueryParameter("form", true, false, "types", query, &params.Types)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter types: %w", err).Error())
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", query, &params.Page)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter page: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	return siw.Handler.GetSearch(c, params)
}

// GetSearchAlbums operation middleware
func (siw *ServerInterfaceWrapper) GetSearchAlbums(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSearchAlbumsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "query" -------------

	err = runtime.BindQueryParameter("form", true, false, "query", query, &params.Query)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter query: %w", err).Error())
	}

	// ------------- Optional query parameter "artist" -------------

	err = runtime.BindQueryParameter("form", true, false, "artist", query, &params.Artist)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter artist: %w", err).Error())
	}

	// ------------- Optional query parameter "genre" -------------

	err = runtime.BindQueryParameter("form", true, false, "genre", query, &params.Genre)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter genre: %w", err).Error())
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", query, &params.Sort)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter sort: %w", err).Error())
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", query, &params.Page)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter page: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	return siw.Handler.GetSearchAlbums(c, params)
}

// GetSearchArtists operation middleware
func (siw *ServerInterfaceWrapper) GetSearchArtists(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSearchArtistsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "query" -------------

	err = runtime.BindQueryParameter("form", true, false, "query", query, &params.Query)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter query: %w", err).Error())
	}

	// ------------- Optional query parameter "genre" -------------

	err = runtime.BindQueryParameter("form", true, false, "genre", query, &params.Genre)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter genre: %w", err).Error())
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", query, &params.Sort)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter sort: %w", err).Error())
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", query, &params.Page)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter page: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	return siw.Handler.GetSearchArtists(c, params)
}

// GetSearchGenres operation middleware
func (siw *ServerInterfaceWrapper) GetSearchGenres(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSearchGenresParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "query" -------------

	err = runtime.BindQueryParameter("form", true, false, "query", query, &params.Query)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter query: %w", err).Error())
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", query, &params.Sort)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter sort: %w", err).Error())
	}

	return siw.Handler.GetSearchGenres(c, params)
}

// GetSearchPlaylists operation middleware
func (siw *ServerInterfaceWrapper) GetSearchPlaylists(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSearchPlaylistsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "query" -------------

	err = runtime.BindQueryParameter("form", true, false, "query", query, &params.Query)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter query: %w", err).Error())
	}

	// ------------- Optional query parameter "owner" -------------

	err = runtime.BindQueryParameter("form", true, false, "owner", query, &params.Owner)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter owner: %w", err).Error())
	}

	// ------------- Optional query parameter "isPublic" -------------

	err = runtime.BindQueryParameter("form", true, false, "isPublic", query, &params.IsPublic)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter isPublic: %w", err).Error())
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", query, &params.Sort)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter sort: %w", err).Error())
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", query, &params.Page)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter page: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	return siw.Handler.GetSearchPlaylists(c, params)
}

// GetSearchSongs operation middleware
func (siw *ServerInterfaceWrapper) GetSearchSongs(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSearchSongsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "query" -------------

	err = runtime.BindQueryParameter("form", true, false, "query", query, &params.Query)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter query: %w", err).Error())
	}

	// ------------- Optional query parameter "artist" -------------

	err = runtime.BindQueryParameter("form", true, false, "artist", query, &params.Artist)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter artist: %w", err).Error())
	}

	// ------------- Optional query parameter "genre" -------------

	err = runtime.BindQueryParameter("form", true, false, "genre", query, &params.Genre)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter genre: %w", err).Error())
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", query, &params.Sort)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter sort: %w", err).Error())
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameter("form", true, false, "order", query, &params.Order)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter order: %w", err).Error())
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", query, &params.Page)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter page: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	return siw.Handler.GetSearchSongs(c, params)
}

// GetSongs operation middleware
func (siw *ServerInterfaceWrapper) GetSongs(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSongsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", query, &params.Page)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter page: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "genre" -------------

	err = runtime.BindQueryParameter("form", true, false, "genre", query, &params.Genre)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter genre: %w", err).Error())
	}

	// ------------- Optional query parameter "artist" -------------

	err = runtime.BindQueryParameter("form", true, false, "artist", query, &params.Artist)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter artist: %w", err).Error())
	}

	// ------------- Optional query parameter "album" -------------

	err = runtime.BindQueryParameter("form", true, false, "album", query, &params.Album)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter album: %w", err).Error())
	}

	return siw.Handler.GetSongs(c, params)
}

// PostSongs operation middleware
func (siw *ServerInterfaceWrapper) PostSongs(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostSongs(c)
}

// DeleteSongsSongId operation middleware
func (siw *ServerInterfaceWrapper) DeleteSongsSongId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "songId" -------------
	var songId SongId

	err = runtime.BindStyledParameter("simple", false, "songId", c.Params("songId"), &songId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter songId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.DeleteSongsSongId(c, songId)
}

// GetSongsSongId operation middleware
func (siw *ServerInterfaceWrapper) GetSongsSongId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "songId" -------------
	var songId SongId

	err = runtime.BindStyledParameter("simple", false, "songId", c.Params("songId"), &songId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter songId: %w", err).Error())
	}

	return siw.Handler.GetSongsSongId(c, songId)
}

// PutSongsSongId operation middleware
func (siw *ServerInterfaceWrapper) PutSongsSongId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "songId" -------------
	var songId SongId

	err = runtime.BindStyledParameter("simple", false, "songId", c.Params("songId"), &songId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter songId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PutSongsSongId(c, songId)
}

// GetSongsSongIdContributors operation middleware
func (siw *ServerInterfaceWrapper) GetSongsSongIdContributors(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "songId" -------------
	var songId SongId

	err = runtime.BindStyledParameter("simple", false, "songId", c.Params("songId"), &songId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter songId: %w", err).Error())
	}

	return siw.Handler.GetSongsSongIdContributors(c, songId)
}

// PostSongsSongIdContributors operation middleware
func (siw *ServerInterfaceWrapper) PostSongsSongIdContributors(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "songId" -------------
	var songId SongId

	err = runtime.BindStyledParameter("simple", false, "songId", c.Params("songId"), &songId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter songId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostSongsSongIdContributors(c, songId)
}

// PostStreams operation middleware
func (siw *ServerInterfaceWrapper) PostStreams(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostStreams(c)
}

// PostTips operation middleware
func (siw *ServerInterfaceWrapper) PostTips(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostTips(c)
}

// GetUsers operation middleware
func (siw *ServerInterfaceWrapper) GetUsers(c *fiber.Ctx) error {

	var err error

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsersParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", query, &params.Page)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter page: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	return siw.Handler.GetUsers(c, params)
}

// PostUsers operation middleware
func (siw *ServerInterfaceWrapper) PostUsers(c *fiber.Ctx) error {

	return siw.Handler.PostUsers(c)
}

// DeleteUsersUserId operation middleware
func (siw *ServerInterfaceWrapper) DeleteUsersUserId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameter("simple", false, "userId", c.Params("userId"), &userId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter userId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.DeleteUsersUserId(c, userId)
}

// GetUsersUserId operation middleware
func (siw *ServerInterfaceWrapper) GetUsersUserId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameter("simple", false, "userId", c.Params("userId"), &userId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter userId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetUsersUserId(c, userId)
}

// PutUsersUserId operation middleware
func (siw *ServerInterfaceWrapper) PutUsersUserId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameter("simple", false, "userId", c.Params("userId"), &userId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter userId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PutUsersUserId(c, userId)
}

// GetUsersUserIdLibraryAlbums operation middleware
func (siw *ServerInterfaceWrapper) GetUsersUserIdLibraryAlbums(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameter("simple", false, "userId", c.Params("userId"), &userId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter userId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetUsersUserIdLibraryAlbums(c, userId)
}

// GetUsersUserIdLibraryPurchases operation middleware
func (siw *ServerInterfaceWrapper) GetUsersUserIdLibraryPurchases(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameter("simple", false, "userId", c.Params("userId"), &userId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter userId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsersUserIdLibraryPurchasesParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", query, &params.Page)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter page: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	return siw.Handler.GetUsersUserIdLibraryPurchases(c, userId, params)
}

// GetUsersUserIdLibrarySongs operation middleware
func (siw *ServerInterfaceWrapper) GetUsersUserIdLibrarySongs(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameter("simple", false, "userId", c.Params("userId"), &userId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter userId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetUsersUserIdLibrarySongs(c, userId)
}

// GetUsersUserIdPlaylists operation middleware
func (siw *ServerInterfaceWrapper) GetUsersUserIdPlaylists(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameter("simple", false, "userId", c.Params("userId"), &userId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter userId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetUsersUserIdPlaylists(c, userId)
}

// PostUsersUserIdPlaylists operation middleware
func (siw *ServerInterfaceWrapper) PostUsersUserIdPlaylists(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameter("simple", false, "userId", c.Params("userId"), &userId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter userId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostUsersUserIdPlaylists(c, userId)
}

// GetUsersUserIdRecent operation middleware
func (siw *ServerInterfaceWrapper) GetUsersUserIdRecent(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameter("simple", false, "userId", c.Params("userId"), &userId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter userId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsersUserIdRecentParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", query, &params.Page)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter page: %w", err).Error())
	}

	return siw.Handler.GetUsersUserIdRecent(c, userId, params)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(m)
	}

	router.Get(options.BaseURL+"/albums", wrapper.GetAlbums)

	router.Post(options.BaseURL+"/albums", wrapper.PostAlbums)

	router.Delete(options.BaseURL+"/albums/:albumId", wrapper.DeleteAlbumsAlbumId)

	router.Get(options.BaseURL+"/albums/:albumId", wrapper.GetAlbumsAlbumId)

	router.Put(options.BaseURL+"/albums/:albumId", wrapper.PutAlbumsAlbumId)

	router.Get(options.BaseURL+"/albums/:albumId/contributors", wrapper.GetAlbumsAlbumIdContributors)

	router.Post(options.BaseURL+"/albums/:albumId/contributors", wrapper.PostAlbumsAlbumIdContributors)

	router.Get(options.BaseURL+"/albums/:albumId/songs", wrapper.GetAlbumsAlbumIdSongs)

	router.Get(options.BaseURL+"/artists", wrapper.GetArtists)

	router.Post(options.BaseURL+"/artists", wrapper.PostArtists)

	router.Get(options.BaseURL+"/artists/:artistId", wrapper.GetArtistsArtistId)

	router.Put(options.BaseURL+"/artists/:artistId", wrapper.PutArtistsArtistId)

	router.Get(options.BaseURL+"/artists/:artistId/songs", wrapper.GetArtistsArtistIdSongs)

	router.Post(options.BaseURL+"/createAdmin", wrapper.PostCreateAdmin)

	router.Get(options.BaseURL+"/flags", wrapper.GetFlags)

	router.Post(options.BaseURL+"/flags", wrapper.PostFlags)

	router.Get(options.BaseURL+"/flags/:flagsId", wrapper.GetFlagsFlagsId)

	router.Post(options.BaseURL+"/flags/:flagsId/review", wrapper.PostFlagsFlagsIdReview)

	router.Post(options.BaseURL+"/flags/:songId", wrapper.PostFlagsSongId)

	router.Get(options.BaseURL+"/genres", wrapper.GetGenres)

	router.Post(options.BaseURL+"/genres", wrapper.PostGenres)

	router.Get(options.BaseURL+"/genres/:genreId", wrapper.GetGenresGenreId)

	router.Put(options.BaseURL+"/genres/:genreId", wrapper.PutGenresGenreId)

	router.Post(options.BaseURL+"/login", wrapper.PostLogin)

	router.Delete(options.BaseURL+"/playlists/:playlistId", wrapper.DeletePlaylistsPlaylistId)

	router.Get(options.BaseURL+"/playlists/:playlistId", wrapper.GetPlaylistsPlaylistId)

	router.Put(options.BaseURL+"/playlists/:playlistId", wrapper.PutPlaylistsPlaylistId)

	router.Get(options.BaseURL+"/playlists/:playlistId/songs", wrapper.GetPlaylistsPlaylistIdSongs)

	router.Post(options.BaseURL+"/playlists/:playlistId/songs", wrapper.PostPlaylistsPlaylistIdSongs)

	router.Delete(options.BaseURL+"/playlists/:playlistId/songs/:songId", wrapper.DeletePlaylistsPlaylistIdSongsSongId)

	router.Post(options.BaseURL+"/purchases/albums", wrapper.PostPurchasesAlbums)

	router.Post(options.BaseURL+"/purchases/songs", wrapper.PostPurchasesSongs)

	router.Get(options.BaseURL+"/search", wrapper.GetSearch)

	router.Get(options.BaseURL+"/search/albums", wrapper.GetSearchAlbums)

	router.Get(options.BaseURL+"/search/artists", wrapper.GetSearchArtists)

	router.Get(options.BaseURL+"/search/genres", wrapper.GetSearchGenres)

	router.Get(options.BaseURL+"/search/playlists", wrapper.GetSearchPlaylists)

	router.Get(options.BaseURL+"/search/songs", wrapper.GetSearchSongs)

	router.Get(options.BaseURL+"/songs", wrapper.GetSongs)

	router.Post(options.BaseURL+"/songs", wrapper.PostSongs)

	router.Delete(options.BaseURL+"/songs/:songId", wrapper.DeleteSongsSongId)

	router.Get(options.BaseURL+"/songs/:songId", wrapper.GetSongsSongId)

	router.Put(options.BaseURL+"/songs/:songId", wrapper.PutSongsSongId)

	router.Get(options.BaseURL+"/songs/:songId/contributors", wrapper.GetSongsSongIdContributors)

	router.Post(options.BaseURL+"/songs/:songId/contributors", wrapper.PostSongsSongIdContributors)

	router.Post(options.BaseURL+"/streams", wrapper.PostStreams)

	router.Post(options.BaseURL+"/tips", wrapper.PostTips)

	router.Get(options.BaseURL+"/users", wrapper.GetUsers)

	router.Post(options.BaseURL+"/users", wrapper.PostUsers)

	router.Delete(options.BaseURL+"/users/:userId", wrapper.DeleteUsersUserId)

	router.Get(options.BaseURL+"/users/:userId", wrapper.GetUsersUserId)

	router.Put(options.BaseURL+"/users/:userId", wrapper.PutUsersUserId)

	router.Get(options.BaseURL+"/users/:userId/library/albums", wrapper.GetUsersUserIdLibraryAlbums)

	router.Get(options.BaseURL+"/users/:userId/library/purchases", wrapper.GetUsersUserIdLibraryPurchases)

	router.Get(options.BaseURL+"/users/:userId/library/songs", wrapper.GetUsersUserIdLibrarySongs)

	router.Get(options.BaseURL+"/users/:userId/playlists", wrapper.GetUsersUserIdPlaylists)

	router.Post(options.BaseURL+"/users/:userId/playlists", wrapper.PostUsersUserIdPlaylists)

	router.Get(options.BaseURL+"/users/:userId/recent", wrapper.GetUsersUserIdRecent)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xda2/cOHf+K4Ra4N1FZc8l9ibxpzpOk+aFd2vECYp2EQS0xJnhRhK1JGVnasx/L3iR",
	"REnUbUYzIyf+ZmtIiuJ5+JzDQ57DR8cjYUwiFHHmXDw6MaQwRBxR+R8M7pLwgy/+9BHzKI45JpFz4Xx4",
	"C8gC8BUCsojjOlg8jiFfOa4TwRA5F1lt16Ho7wRT5DsXnCbIdZi3QiEUzS4IDSF3LpwkwaIkX8eiKuMU",
	"R0tns3EdSDlmvKUTskxNL9L6u3VjEcAla+6FKGLvQ1p5ty4sUURRcxdkEXsf0tq79SHAIebVHvyRhHeI",
	"il5gjkIGYkRBDJdZV/5OEF3nfVGtmG/20QImAXcu5lPXCeF3HCahczGbTrNO4IijJaKyF7LpSidu4BKB",
	"tJj9xbpPlvfO7C8K4DpohV9ayj7wRhu7jT0j0bK5I6KEvRO67m4dSBiizR0QJewd0HV36cAmLSy56VIS",
	"j6AsSmJEOUaKsgy6aGnQdTxyj+iHEC7RZxqIGug7DONAFFpxHrOLycTzo9MwYdiDcXzqkXAiWY1NZtPZ",
	"RFY//SsWY56/i2LrqyiCHPmXvNAxH3J0wnGI5MBA/7+iYJ0OTKWJwqCbfb0iQYA88VzIgSQU3CHGJRqY",
	"rS/YOjqt78fsqyCyJZLVa4rfERIgGDmSK74pmdQUjSRpiJIxxR4qfNPr09evjUFdBARypzpFRa8DBBl6",
	"C3mxAWc+nb84mc5O5lNTOuaAVz6QYx6UWnkvxcY4+E/MrWOZxP5uct2YU+JP3QdD7X3JapC7v5DHxUsv",
	"lb6rAf8fcsaZX/FphcBH4n0Db2Dk7wmdW4IqJBFfBetrzDiKtNmRdXw2P58KFVDTigGDncVgslsrb9wj",
	"ihdYzYOss6rZ9mnxAIMA8TcwgFEJ9OJzT88tsG/7/hKGMq418GCD0RWJOMV3CSd0ZyLVLWESfZI/mvBb",
	"IMgT0bf9II+SNQz4+gZRD0Vcmwb5oJ534pGh57FhdlYGxyaL/6DUJgWP+MXPOZue2brvIw5xwKrTXvQJ",
	"MY58qQ7AA2QgIhwsSGJnghAxVh5C5yNiJKEeaqpa+n7Z8bw52ye/E/Zy9YsVIL5CbuPzlyfz6afZ/GI6",
	"vZhO/7eO2fuq0qI581aOJfIB+h4HMIKpYjVsfHOMMVNDmzDEQBLBhK8Ixf8nRlwWYmBBSQjCNXgg9Fu9",
	"Pi524jLh5GQpKFGMBkgi/HeCAPZRxAX10EInZvMX6Oz8t5cn6NXru5PZ3H9xAs/Ofzs5m//22+xs9vJs",
	"Oi1owa7kTBFkthG6ghwtCV2no3KPSSCHqdArj8Rripcr/tX8PYTfr1G05KuieW++NCaUI/pV0NhX3Gpv",
	"AlUBR0v5SMw2FPEhxqfSNcYhT1hh3eDEKPKxNLtLY5RQiiIOVJ0yfiJhu/5pVKboHqMHyZE+ZiFmTP4N",
	"pVmHpBmQf09erWrDQLpEvGXYtBmXjhX4RQKYULWa/3UvY6c7xrV2KHZN0KLoXNqhOyTEmVqb+XjpBY5y",
	"OhSGRP9SZ5+10cn5DnRSYr4Kfk2hFMchm2EZtGw8+V4u6itEWbsckOWBt4IUehwpKrpbA/GztFoAjhin",
	"SSh9PgMuD/qto6Q/gk0o8b51XEJFFbtW2LStmkhWK85O2yjfpIt4iw7uv0pMF/1sMp+OaKV4K5aE4AMI",
	"yD0CnIBAmt2Ak0GXiTfJXYC9wpsXMGBWa9iy5vp9Dd7Be0IxR+C2bg17SIO/zrxWfbeCKaHeCjLLrPWk",
	"WvDWxU/+fPt2QAnEcC0m922mrUydLP7gdls81r2+qSzHZ3NzNZ772KqGaNrGcSVT/BI3H/Xy4NiEJzBn",
	"WQ/lvvBWXddr7aQKs6+Cp+SbpAtV/FHVoeoBpBSuZdXEx6Q7KUmH0OTlq9cTWfE0jF904aMt6C9/06GZ",
	"L6GwxqrXvwAcAYY8EvnMtHPmL17a4Gz43FsFeSC3mlAt7IokEbf4Sjo5S2JlbG4jTl21I3Sqfr3Z6XwQ",
	"v975yex8F7/e5QNiJFT65ShuvfK8N6BrzGvX2LaJNZeZI2Ojr88MWRwJd5iUtKwQsDQEqFqg/oEewP/U",
	"rFAHmJkohLiEt7/IKvp3/a/AmSlQVdzSzgJTm4vzn2QVDTopcx9r2Yjp4PmGti6+JVZ0xpCxB0L91rEp",
	"1nSdB2Eh5R0RTa1IhNReXLG1f5vNX4hF3KvXU/s8JQscoJ4kL7Qtm8zmLya6fkeaH8h0qy4HxJh99W2j",
	"XJqNOYYMWRmtuhn8MhwYcqpOuo3rMOQlFPP1rbdCWo+/QZAiepnwlZyA8r936ef+878/pRuREjzy17zj",
	"YtDVlheOFsTiHrr5ABaEghBGcCnWylIyav3OXLX140r3CHMBjHyQWkTsNDNcL5wrCh8CcHnzwZE+baba",
	"np1OT6dilEmMIhhj58J5IR+5ck9PfpveBhN/LpEUpCAbyV9CWzrvEb9UJdzCmYI/H51/pWjhXDj/MslP",
	"HkzyIhO5RbtxW8upPWRRsDgy73DAEZULXik58OFtzWZwdmqg+xbkF4EjFpOIKRHPp1O1QlQ+J2EmxnGA",
	"PTkQk7+08yxvf0vnLuSwxiAtGoy2IdNbphO1X1oxIjcWDbKLD7g8M8qrUedSLjoBWWiwqtmThCGka+fC",
	"uRY/wiBIf3UdDpcCOI7G0xfBV4RZMHdDWA467fd+Q/x1Lwl1GMIim2jqLcFidlxYdP2SgwtfvBdoa0K8",
	"7UxNoGKpN9BP9y0K3Crpw2TVP7+IGZmD50o2DCCI0EN2MqmCn42b0tfkUa/qNqoTYmVcxdVb+VxVv8zO",
	"NPVjtXT1aGGQswNC5RjSVsOqpf2iKu13hN5h30dRP1krqdRL2W1RTHuQ5PR50jfBQO1QShicWSwaWSp/",
	"VVEtvEdciVoodqnRbWohsWmFZFCBH1WrPAOsAWB6WTE0z3yWzfbTJhMvP1nRwUbWyLwyK/04tHRVGotO",
	"1qp5NOX4Nuu1tlgLYq0jKK8oxi3M1+HxMDxrFQQ0bovYKx5z6v5Vh4aZ8XYAfX8fFvKl75sABZz0ZDZ1",
	"qLQrpaXbdz8Kl92mX9+JxKRzeTzsJb/gH0yfC97RDsvaqQBHbaBlAFJe7kbE6CLH8xSl5zn1YZ0af1F2",
	"6tP0GJWdv+PCbObD7uYiUsVH5SPS2KhzEmXQyUCon7To2azeXix6PY4jdxRl4Oj0LQfHgPLeHshXpF6m",
	"9zGscDLIbPKYbuNtOvDaZb7l11MNphVHyiljhk2rt0EVa1RzqkjF32ASTJ3DYVjJH5ehnqHWDLU9+x3S",
	"TaqujNTBQi+ic0sbPYOoO7ShNj62u+5jRY3N6pdf0G72dyVEm+GfWVOm5a8096UfYimfemPsyii4Pd0V",
	"5dbnBKFlKMfEiceBTQi5t8LRUoWUs61sq8sIQC3VDCryfwUQGRXfRFTvZIERsUHW405EIOObjk8Easke",
	"lIM++klUfIsRWpOK83fia5m1LLhyUQ4xu0vn2xvilmrCUDqe6FSFs4DGmiCUlpN/6QsLzWV9/LIV/8x+",
	"WP650hFA6ZHYwdd9XZCcsdPkUafu2LTy1Lssx0c/QyrNDTIqs+fJEt1OJGdroEF15eCYqFPRzWaOiZKP",
	"qvxuWBmCSfOIxq1CEp+NqUZEKjFvB0ZdF/ZDpMrzsumAxNs0I0w/COpEMkdmq8OKUYwtgCq7zhC6xpSb",
	"Nq8btMt7VWJE2iHvcyf1oOJXx7SrYK5pqpsKy3TAU3lpCTRbuIaYhvfX6SEct7tumcYpd/mSwxsHMig6",
	"3U3YWLcC0vRpJcG7lhk7edSROZv2ufs+j+HpxbVp7M+oTMMnIOU2578q1eTqkh9Zcf2bPFDj+R9S4M80",
	"MlaAZS7/jc1j341GArJsc4xeyyJDmfpZAF57jJ0ZkpaVzh62eTzSZpsCpkaNQE6+Ibv3KNGxlU3QlPGX",
	"h0fmbeJ5iLFFEgAFLcl+s8G4QyWosrz4s5HyyAU4uocB9oWmlbmKYFC2s8T4qC4WChnmccJX4qlnumPy",
	"hBqPeULNDmEbaVoPdmOm4ex50Civ+lPFb6RDtucQDiN9agqBTGqNgRz7l+3xOCg20tE0Tcssbc3hGceA",
	"R7O9lRVsMrnSD65YXUUs1Blee8HC8BaYIa5Rq8CnBL/9HsBoYad63dR+EMOC2e0OY4yVxHqePx3ZyQkp",
	"P4CjHALDEFz5+ESJ4GqXA/uDyyA7CVl28n45m3S9533QkjlPoqUKAgGclBA4dECIzP5ovmU7qivsPvS2",
	"yiWUt9yUMAHt7rCFcfZjw4mikNwjX6X7KUJqOLX5Ub5EYar4ogZUpclJjLQiDTyYlt452cP2Gd50Frnf",
	"EV8RX9UZPosdNCKWi68bP1uWzEkjH2KjOZmWO4I5qV8N8hSJg5Nt9g4YVcLuMlRX5kRmR3aYEqlBMMyM",
	"sKC8RCuc4hgBXQ6EsqBevlWSJ3c1EAaYOSzXI88T54eaOOkdN3XThiFIvVXTqutWlajYGCVky1KAIxrW",
	"hAOm/9ZfaFMZzEoedRKG8IQh0ROO/Gx/Ok2DLRpgwjJTX6XydDNXZ/nSZ//dzCZz1dbkrzUdlq3Zbz9y",
	"bA3b4PAjn/WniMnB2E+irSzh487hmO5ABzDy6626N3VjWI3l1tgAwdGuwwmHwUcpimLu4rO59eKTaiq+",
	"A1vWampS3ePSuj8gdzBIpy/0KGFMnjEpzHCDzjQ5mVzWIdWeqlWXcK+W2MAvKmOFTAf4awvN9aC1Sgo+",
	"0RQgtFcqvh5vUbv1rS9Jt2V7vOOWUA4WGAU++CUmcRJAoa5cnYL1qw85cmVe1rrRY4TWXHTn5O2ZF0KY",
	"D83XGAlgy2nHf252pjlV7EbPkngMVIyJZCpROdbciXpqq9/AA+YrAP17GHlizS9nSyvVtGdr0FxTl7Oh",
	"iWxyMtgL2RycBoL00jK36Zt2ooDsFWl7z9N+y2lfa0w9rXlvzYeRTnz141Yzv/0csqqVnWXqPu/zeTng",
	"tK+ZknubiHWTb5zbbbvNldr1wpOaKtZD3hqYlSPetilRWB01z4rcod1nYmQ7gtKiE0rLKLwXFUkeIkRB",
	"mue8UU3Kotu+J5Y3AE1iiu8hR81plbL7ghrTKnUlgPz6QDe/+msvjGBcVFi4ZuzZQN+NfZpcDE+KgHL+",
	"sHJQbHBGEw21HiNRlWqOAjTQT8Y6wZpijz07ALZ0AKQXtxzCB2BcEtPEMpaPINSvvRY//c3WRdGU0Tko",
	"/5MPnx7BLaCHFBO1enjLzKivW6qSIe62pZXeVtJKLN38xiPqnsUZPZre2Ur01UeNjuqCKpmfd/JQt2sO",
	"narHpjXUobR+K7xWBbLdKbLB0m8q+h6Stne6BKZP69J/Xt+43uOvb3tMBhx7islt86Be26TJYnrLZy7T",
	"RFVN5y13PUvRPnrjPnvA9D2YHb7DPcZxtsOkBi2dNzAznPU99bjLEcef9tDifmOPaqTrNuvKJ50742lN",
	"8rbYIlmo6di9PIhajiky6L8mnmgwOR9Td4w9desxgbXfqKHOWqPzVTEGIHe6GGSMJOT9NFfESDaquSGm",
	"s006NAqeb4d5vh2m7naYJiLjFMG2YI1bXWioI+nSmUTXV1rmIfx+jaKl+Ji57Tp4dI89lCbwtNzyfJNn",
	"7stcnvqa5+q1zs8hbsOqYQkNQJFH6F7g/FG2DCBQSDVhLB+Inioocxy34PiTKDFYpFGYukQ73ISfZVrv",
	"4ik1BLZFzFIJt+Zl9arHTz+gguPYsghSuVNsG8+uwymMmEp6WTdox956/IRjwFDEAcuSwATr4efTLYp8",
	"wHEsbw0r30sgJ4iaTfLa8SZb9jNDdO8O5zEZuGJEel0ioJIIjci7qmQ68GIpc88mrLh/oQDSbAqnINqH",
	"/apzOI2byZ5iliqZ/Km349bumZWfWcVMxkCTRxUP2MEzK+t+TqMH+9GSDjr8qTyzUoz79czWSNdtViqD",
	"y/C4OmPMs7jNMysLlTyzfTKxi++vOG4NxVDjuB0MBsfUKs+oq0Pdft22nVXKJMB3FNJ1h+A8A5DXqlJd",
	"oN4TJKlhYmOP5q1Nw+v9LKBqWFilPPYPVn1VDjMNi2agZfkg+mEtj4/fFm4/9KHlwqh2O56cZVoYHYoP",
	"AV+wwowTecipF3xbD6FVobvdsbQxsiR7yteG58Rl3CC4Z4osH9dqhFinOB0DXg3BOk8QW0PmcDgexvJQ",
	"if2hyxJv0TX14vDoOXZq2dlzatkOqWUPc8SwQ4a8EuVR5Gm5deC7j6rw/uy//IR3J0NxrGm2n5JyriK0",
	"LysqCAVriT7kgzBhMgazsvaVDdN7e0BZQDwYrIjEbkID58JZcR5fTCbZDxevpq/mUui65cf0dLwO+xS4",
	"0U+udbYD81kWuJ8/kbdobL5s/j8AAP//2zNsMr22AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
