// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for FlagStatus.
const (
	FlagStatusActioned  FlagStatus = "actioned"
	FlagStatusDismissed FlagStatus = "dismissed"
	FlagStatusPending   FlagStatus = "pending"
	FlagStatusReviewed  FlagStatus = "reviewed"
)

// Defines values for FlagTargetType.
const (
	FlagTargetTypeAlbum FlagTargetType = "album"
	FlagTargetTypeSong  FlagTargetType = "song"
)

// Defines values for PostFlagsJSONBodyTargetType.
const (
	PostFlagsJSONBodyTargetTypeAlbum PostFlagsJSONBodyTargetType = "album"
	PostFlagsJSONBodyTargetTypeSong  PostFlagsJSONBodyTargetType = "song"
)

// Defines values for PostFlagsFlagsIdReviewJSONBodyStatus.
const (
	PostFlagsFlagsIdReviewJSONBodyStatusActioned  PostFlagsFlagsIdReviewJSONBodyStatus = "actioned"
	PostFlagsFlagsIdReviewJSONBodyStatusDismissed PostFlagsFlagsIdReviewJSONBodyStatus = "dismissed"
	PostFlagsFlagsIdReviewJSONBodyStatusPending   PostFlagsFlagsIdReviewJSONBodyStatus = "pending"
	PostFlagsFlagsIdReviewJSONBodyStatusReviewed  PostFlagsFlagsIdReviewJSONBodyStatus = "reviewed"
)

// Defines values for GetSearchArtistsParamsSort.
const (
	GetSearchArtistsParamsSortListeners  GetSearchArtistsParamsSort = "listeners"
	GetSearchArtistsParamsSortName       GetSearchArtistsParamsSort = "name"
	GetSearchArtistsParamsSortPopularity GetSearchArtistsParamsSort = "popularity"
)

// Defines values for GetSearchGenresParamsSort.
const (
	GetSearchGenresParamsSortName       GetSearchGenresParamsSort = "name"
	GetSearchGenresParamsSortPopularity GetSearchGenresParamsSort = "popularity"
)

// Defines values for GetSearchMediaParamsSort.
const (
	GetSearchMediaParamsSortDuration    GetSearchMediaParamsSort = "duration"
	GetSearchMediaParamsSortPopularity  GetSearchMediaParamsSort = "popularity"
	GetSearchMediaParamsSortReleaseDate GetSearchMediaParamsSort = "release_date"
	GetSearchMediaParamsSortTitle       GetSearchMediaParamsSort = "title"
)

// Defines values for GetSearchMediaParamsOrder.
const (
	Asc  GetSearchMediaParamsOrder = "asc"
	Desc GetSearchMediaParamsOrder = "desc"
)

// Defines values for GetSearchPlaylistsParamsSort.
const (
	GetSearchPlaylistsParamsSortCreatedAt  GetSearchPlaylistsParamsSort = "created_at"
	GetSearchPlaylistsParamsSortPopularity GetSearchPlaylistsParamsSort = "popularity"
	GetSearchPlaylistsParamsSortTitle      GetSearchPlaylistsParamsSort = "title"
	GetSearchPlaylistsParamsSortUpdatedAt  GetSearchPlaylistsParamsSort = "updated_at"
)

// Album defines model for Album.
type Album struct {
	ArtistId      openapi_types.UUID  `json:"artistId"`
	CoverImageUrl *string             `json:"coverImageUrl,omitempty"`
	CreatedAt     *time.Time          `json:"createdAt,omitempty"`
	Description   *string             `json:"description,omitempty"`
	Id            *openapi_types.UUID `json:"id,omitempty"`
	IsFlagged     *bool               `json:"is_flagged,omitempty"`
	Likes         *float32            `json:"likes,omitempty"`
	Price         *int                `json:"price,omitempty"`
	ReleaseDate   *time.Time          `json:"releaseDate,omitempty"`
	Title         string              `json:"title"`
	UpdatedAt     *time.Time          `json:"updatedAt,omitempty"`
}

// Artist defines model for Artist.
type Artist struct {
	ArtistName       string              `json:"artistName"`
	CreatedAt        *time.Time          `json:"createdAt,omitempty"`
	Id               *openapi_types.UUID `json:"id,omitempty"`
	MonthlyListeners *int                `json:"monthlyListeners,omitempty"`
	UpdatedAt        *time.Time          `json:"updatedAt,omitempty"`
	UserId           openapi_types.UUID  `json:"userId"`
	Verified         *bool               `json:"verified,omitempty"`
	WalletBalance    *int                `json:"walletBalance,omitempty"`
}

// Contributor defines model for Contributor.
type Contributor struct {
	ArtistId          openapi_types.UUID `json:"artistId"`
	ContributionType  string             `json:"contributionType"`
	CreatedAt         *time.Time         `json:"createdAt,omitempty"`
	RoyaltyPercentage *int               `json:"royaltyPercentage,omitempty"`
	UpdatedAt         *time.Time         `json:"updatedAt,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Code    int     `json:"code"`
	Details *string `json:"details,omitempty"`
	Message string  `json:"message"`
}

// Flag defines model for Flag.
type Flag struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Description Detailed explanation of the flag
	Description *string `json:"description,omitempty"`

	// Id Auto-generated unique identifier
	Id *openapi_types.UUID `json:"id,omitempty"`

	// Reason Category of the violation
	Reason string `json:"reason"`

	// ReporterUserId ID of the user reporting the content
	ReporterUserId openapi_types.UUID `json:"reporter_user_id"`

	// Status Current status of the flag
	Status FlagStatus `json:"status"`

	// TargetId ID of the flagged content (song or album)
	TargetId openapi_types.UUID `json:"target_id"`

	// TargetType Type of content being flagged
	TargetType FlagTargetType `json:"target_type"`
	UpdatedAt  *time.Time     `json:"updated_at,omitempty"`
}

// FlagStatus Current status of the flag
type FlagStatus string

// FlagTargetType Type of content being flagged
type FlagTargetType string

// Genre defines model for Genre.
type Genre struct {
	Description string              `json:"description"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	ImageUrl    *string             `json:"imageUrl,omitempty"`
	Name        string              `json:"name"`
}

// Playlist defines model for Playlist.
type Playlist struct {
	CoverImageUrl *string             `json:"coverImageUrl,omitempty"`
	CreatedAt     *time.Time          `json:"createdAt,omitempty"`
	Description   *string             `json:"description,omitempty"`
	Id            *openapi_types.UUID `json:"id,omitempty"`
	IsPublic      *bool               `json:"isPublic,omitempty"`
	Title         string              `json:"title"`
	UpdatedAt     *time.Time          `json:"updatedAt,omitempty"`
	UserId        openapi_types.UUID  `json:"userId"`
}

// Purchase defines model for Purchase.
type Purchase struct {
	Currency      string              `json:"currency"`
	Id            *openapi_types.UUID `json:"id,omitempty"`
	PaymentStatus string              `json:"paymentStatus"`
	PurchasePrice int                 `json:"purchasePrice"`
	PurchasedAt   *time.Time          `json:"purchasedAt,omitempty"`
	UserId        openapi_types.UUID  `json:"userId"`
}

// Song defines model for Song.
type Song struct {
	AlbumId       *openapi_types.UUID `json:"albumId,omitempty"`
	ArtistId      openapi_types.UUID  `json:"artistId"`
	ArtistsNames  []string            `json:"artists_names"`
	AudioUrl      string              `json:"audioUrl"`
	CoverImageUrl *string             `json:"coverImageUrl,omitempty"`
	CreatedAt     *time.Time          `json:"createdAt,omitempty"`

	// Duration Duration in seconds
	Duration    int                 `json:"duration"`
	GenreId     openapi_types.UUID  `json:"genreId"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	IsFlagged   *bool               `json:"is_flagged,omitempty"`
	Likes       *float32            `json:"likes,omitempty"`
	Lyrics      *string             `json:"lyrics,omitempty"`
	PlaysCount  *int                `json:"playsCount,omitempty"`
	PreviewUrl  *string             `json:"previewUrl,omitempty"`
	Price       int                 `json:"price"`
	ReleaseDate time.Time           `json:"releaseDate"`
	Title       string              `json:"title"`
	UpdatedAt   *time.Time          `json:"updatedAt,omitempty"`
}

// User defines model for User.
type User struct {
	Bio             *string             `json:"bio,omitempty"`
	CreatedAt       *time.Time          `json:"createdAt,omitempty"`
	Email           openapi_types.Email `json:"email"`
	FirstName       string              `json:"firstName"`
	Id              *openapi_types.UUID `json:"id,omitempty"`
	IsArtist        *bool               `json:"isArtist,omitempty"`
	LastName        string              `json:"lastName"`
	Password        *string             `json:"password,omitempty"`
	PhoneNumber     *string             `json:"phoneNumber,omitempty"`
	ProfileImageUrl *string             `json:"profileImageUrl,omitempty"`
	UpdatedAt       *time.Time          `json:"updatedAt,omitempty"`
	Username        string              `json:"username"`
}

// AlbumId defines model for albumId.
type AlbumId = openapi_types.UUID

// ArtistId defines model for artistId.
type ArtistId = openapi_types.UUID

// FlagsId defines model for flagsId.
type FlagsId = openapi_types.UUID

// GenreId defines model for genreId.
type GenreId = openapi_types.UUID

// Limit defines model for limit.
type Limit = int

// Page defines model for page.
type Page = int

// PlaylistId defines model for playlistId.
type PlaylistId = openapi_types.UUID

// SongId defines model for songId.
type SongId = openapi_types.UUID

// UserId defines model for userId.
type UserId = openapi_types.UUID

// GetAlbumsParams defines parameters for GetAlbums.
type GetAlbumsParams struct {
	// Page Page integer
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of items per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Artist Filter by artist ID
	Artist *openapi_types.UUID `form:"artist,omitempty" json:"artist,omitempty"`
}

// GetArtistsParams defines parameters for GetArtists.
type GetArtistsParams struct {
	// Page Page integer
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of items per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Verified Filter by verified status
	Verified *bool `form:"verified,omitempty" json:"verified,omitempty"`
}

// GetArtistsArtistIdAlbumsParams defines parameters for GetArtistsArtistIdAlbums.
type GetArtistsArtistIdAlbumsParams struct {
	// Page Page integer
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of items per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetArtistsArtistIdSongsParams defines parameters for GetArtistsArtistIdSongs.
type GetArtistsArtistIdSongsParams struct {
	// Page Page integer
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of items per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostCreateAdminJSONBody defines parameters for PostCreateAdmin.
type PostCreateAdminJSONBody struct {
	UserId *openapi_types.UUID `json:"userId,omitempty"`
}

// PostFlagsJSONBody defines parameters for PostFlags.
type PostFlagsJSONBody struct {
	Description *string                     `json:"description,omitempty"`
	Reason      string                      `json:"reason"`
	TargetId    openapi_types.UUID          `json:"targetId"`
	TargetType  PostFlagsJSONBodyTargetType `json:"targetType"`
}

// PostFlagsJSONBodyTargetType defines parameters for PostFlags.
type PostFlagsJSONBodyTargetType string

// PostFlagsFlagsIdReviewJSONBody defines parameters for PostFlagsFlagsIdReview.
type PostFlagsFlagsIdReviewJSONBody struct {
	Status *PostFlagsFlagsIdReviewJSONBodyStatus `json:"status,omitempty"`
}

// PostFlagsFlagsIdReviewJSONBodyStatus defines parameters for PostFlagsFlagsIdReview.
type PostFlagsFlagsIdReviewJSONBodyStatus string

// PostLoginJSONBody defines parameters for PostLogin.
type PostLoginJSONBody struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// PostPlaylistsPlaylistIdSongsJSONBody defines parameters for PostPlaylistsPlaylistIdSongs.
type PostPlaylistsPlaylistIdSongsJSONBody struct {
	SongId openapi_types.UUID `json:"songId"`
}

// PostPurchasesAlbumsJSONBody defines parameters for PostPurchasesAlbums.
type PostPurchasesAlbumsJSONBody struct {
	AlbumId         openapi_types.UUID `json:"albumId"`
	PaymentMethodId string             `json:"paymentMethodId"`
	UserId          openapi_types.UUID `json:"userId"`
}

// PostPurchasesSongsJSONBody defines parameters for PostPurchasesSongs.
type PostPurchasesSongsJSONBody struct {
	// PaymentMethodId Stripe payment method ID
	PaymentMethodId string             `json:"paymentMethodId"`
	SongId          openapi_types.UUID `json:"songId"`
	UserId          openapi_types.UUID `json:"userId"`
}

// GetSearchParams defines parameters for GetSearch.
type GetSearchParams struct {
	// Query Search term
	Query string `form:"query" json:"query"`

	// Types Comma-separated list of content types to search (songs,albums,artists,playlists,genres)
	Types *string `form:"types,omitempty" json:"types,omitempty"`

	// Page Page integer
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of items per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetSearchArtistsParams defines parameters for GetSearchArtists.
type GetSearchArtistsParams struct {
	// Query Search term (artist name)
	Query *string `form:"query,omitempty" json:"query,omitempty"`

	// Genre Filter by genre name or ID
	Genre *string `form:"genre,omitempty" json:"genre,omitempty"`

	// Sort Sort field (popularity,listeners,name)
	Sort *GetSearchArtistsParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Page Page integer
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of items per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetSearchArtistsParamsSort defines parameters for GetSearchArtists.
type GetSearchArtistsParamsSort string

// GetSearchGenresParams defines parameters for GetSearchGenres.
type GetSearchGenresParams struct {
	// Query Search term (genre name)
	Query *string `form:"query,omitempty" json:"query,omitempty"`

	// Sort Sort field (popularity,name)
	Sort *GetSearchGenresParamsSort `form:"sort,omitempty" json:"sort,omitempty"`
}

// GetSearchGenresParamsSort defines parameters for GetSearchGenres.
type GetSearchGenresParamsSort string

// GetSearchMediaParams defines parameters for GetSearchMedia.
type GetSearchMediaParams struct {
	// Query Search term (title or lyrics)
	Query *string `form:"query,omitempty" json:"query,omitempty"`

	// Artist Filter by artist name or ID
	Artist *string `form:"artist,omitempty" json:"artist,omitempty"`

	// Genre Filter by genre name or ID
	Genre *string `form:"genre,omitempty" json:"genre,omitempty"`

	// Sort Sort field (popularity,release_date,duration)
	Sort *GetSearchMediaParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Order Sort order
	Order *GetSearchMediaParamsOrder `form:"order,omitempty" json:"order,omitempty"`

	// Page Page integer
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of items per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetSearchMediaParamsSort defines parameters for GetSearchMedia.
type GetSearchMediaParamsSort string

// GetSearchMediaParamsOrder defines parameters for GetSearchMedia.
type GetSearchMediaParamsOrder string

// GetSearchPlaylistsParams defines parameters for GetSearchPlaylists.
type GetSearchPlaylistsParams struct {
	// Query Search term (playlist title or description)
	Query *string `form:"query,omitempty" json:"query,omitempty"`

	// Owner Filter by owner username or ID
	Owner *string `form:"owner,omitempty" json:"owner,omitempty"`

	// IsPublic Filter by public/private status
	IsPublic *bool `form:"isPublic,omitempty" json:"isPublic,omitempty"`

	// Sort Sort field (popularity,created_at,updated_at)
	Sort *GetSearchPlaylistsParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Page Page integer
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of items per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetSearchPlaylistsParamsSort defines parameters for GetSearchPlaylists.
type GetSearchPlaylistsParamsSort string

// GetSongsParams defines parameters for GetSongs.
type GetSongsParams struct {
	// Page Page integer
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of items per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Genre Filter by genre ID
	Genre *string `form:"genre,omitempty" json:"genre,omitempty"`

	// Artist Filter by artist ID
	Artist *string `form:"artist,omitempty" json:"artist,omitempty"`

	// Album Filter by album ID
	Album *string `form:"album,omitempty" json:"album,omitempty"`
}

// PostStreamsJSONBody defines parameters for PostStreams.
type PostStreamsJSONBody struct {
	CountryCode *string            `json:"countryCode,omitempty"`
	DeviceType  *string            `json:"deviceType,omitempty"`
	IsPreview   *bool              `json:"isPreview,omitempty"`
	SongId      openapi_types.UUID `json:"songId"`
}

// PostTipsJSONBody defines parameters for PostTips.
type PostTipsJSONBody struct {
	Amount          int                `json:"amount"`
	ArtistId        openapi_types.UUID `json:"artistId"`
	Message         *string            `json:"message,omitempty"`
	PaymentMethodId string             `json:"paymentMethodId"`
}

// GetUsersParams defines parameters for GetUsers.
type GetUsersParams struct {
	// Page Page integer
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of items per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetUsersUserIdLibraryPurchasesParams defines parameters for GetUsersUserIdLibraryPurchases.
type GetUsersUserIdLibraryPurchasesParams struct {
	// Page Page integer
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of items per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetUsersUserIdRecentParams defines parameters for GetUsersUserIdRecent.
type GetUsersUserIdRecentParams struct {
	// Limit Number of items per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Page Page integer
	Page *Page `form:"page,omitempty" json:"page,omitempty"`
}

// PostAlbumsJSONRequestBody defines body for PostAlbums for application/json ContentType.
type PostAlbumsJSONRequestBody = Album

// PutAlbumsAlbumIdJSONRequestBody defines body for PutAlbumsAlbumId for application/json ContentType.
type PutAlbumsAlbumIdJSONRequestBody = Album

// PostAlbumsAlbumIdContributorsJSONRequestBody defines body for PostAlbumsAlbumIdContributors for application/json ContentType.
type PostAlbumsAlbumIdContributorsJSONRequestBody = Contributor

// PostArtistsJSONRequestBody defines body for PostArtists for application/json ContentType.
type PostArtistsJSONRequestBody = Artist

// PutArtistsArtistIdJSONRequestBody defines body for PutArtistsArtistId for application/json ContentType.
type PutArtistsArtistIdJSONRequestBody = Artist

// PostCreateAdminJSONRequestBody defines body for PostCreateAdmin for application/json ContentType.
type PostCreateAdminJSONRequestBody PostCreateAdminJSONBody

// PostFlagsJSONRequestBody defines body for PostFlags for application/json ContentType.
type PostFlagsJSONRequestBody PostFlagsJSONBody

// PostFlagsFlagsIdReviewJSONRequestBody defines body for PostFlagsFlagsIdReview for application/json ContentType.
type PostFlagsFlagsIdReviewJSONRequestBody PostFlagsFlagsIdReviewJSONBody

// PostGenresJSONRequestBody defines body for PostGenres for application/json ContentType.
type PostGenresJSONRequestBody = Genre

// PutGenresGenreIdJSONRequestBody defines body for PutGenresGenreId for application/json ContentType.
type PutGenresGenreIdJSONRequestBody = Genre

// PostLoginJSONRequestBody defines body for PostLogin for application/json ContentType.
type PostLoginJSONRequestBody PostLoginJSONBody

// PutPlaylistsPlaylistIdJSONRequestBody defines body for PutPlaylistsPlaylistId for application/json ContentType.
type PutPlaylistsPlaylistIdJSONRequestBody = Playlist

// PostPlaylistsPlaylistIdSongsJSONRequestBody defines body for PostPlaylistsPlaylistIdSongs for application/json ContentType.
type PostPlaylistsPlaylistIdSongsJSONRequestBody PostPlaylistsPlaylistIdSongsJSONBody

// PostPurchasesAlbumsJSONRequestBody defines body for PostPurchasesAlbums for application/json ContentType.
type PostPurchasesAlbumsJSONRequestBody PostPurchasesAlbumsJSONBody

// PostPurchasesSongsJSONRequestBody defines body for PostPurchasesSongs for application/json ContentType.
type PostPurchasesSongsJSONRequestBody PostPurchasesSongsJSONBody

// PostSongsJSONRequestBody defines body for PostSongs for application/json ContentType.
type PostSongsJSONRequestBody = Song

// PutSongsSongIdJSONRequestBody defines body for PutSongsSongId for application/json ContentType.
type PutSongsSongIdJSONRequestBody = Song

// PostSongsSongIdContributorsJSONRequestBody defines body for PostSongsSongIdContributors for application/json ContentType.
type PostSongsSongIdContributorsJSONRequestBody = Contributor

// PostStreamsJSONRequestBody defines body for PostStreams for application/json ContentType.
type PostStreamsJSONRequestBody PostStreamsJSONBody

// PostTipsJSONRequestBody defines body for PostTips for application/json ContentType.
type PostTipsJSONRequestBody PostTipsJSONBody

// PostUsersJSONRequestBody defines body for PostUsers for application/json ContentType.
type PostUsersJSONRequestBody = User

// PutUsersUserIdJSONRequestBody defines body for PutUsersUserId for application/json ContentType.
type PutUsersUserIdJSONRequestBody = User

// PostUsersUserIdPlaylistsJSONRequestBody defines body for PostUsersUserIdPlaylists for application/json ContentType.
type PostUsersUserIdPlaylistsJSONRequestBody = Playlist

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all albums
	// (GET /albums)
	GetAlbums(c *fiber.Ctx, params GetAlbumsParams) error
	// Create a new album
	// (POST /albums)
	PostAlbums(c *fiber.Ctx) error
	// Like an album by ID
	// (POST /albums/like/{albumId})
	PostAlbumsLikeAlbumId(c *fiber.Ctx, albumId AlbumId) error
	// Delete album
	// (DELETE /albums/{albumId})
	DeleteAlbumsAlbumId(c *fiber.Ctx, albumId AlbumId) error
	// Get album by ID
	// (GET /albums/{albumId})
	GetAlbumsAlbumId(c *fiber.Ctx, albumId AlbumId) error
	// Update album
	// (PUT /albums/{albumId})
	PutAlbumsAlbumId(c *fiber.Ctx, albumId AlbumId) error
	// Get album contributors
	// (GET /albums/{albumId}/contributors)
	GetAlbumsAlbumIdContributors(c *fiber.Ctx, albumId AlbumId) error
	// Add contributor to album
	// (POST /albums/{albumId}/contributors)
	PostAlbumsAlbumIdContributors(c *fiber.Ctx, albumId AlbumId) error
	// Get album's songs
	// (GET /albums/{albumId}/songs)
	GetAlbumsAlbumIdSongs(c *fiber.Ctx, albumId AlbumId) error
	// List all artists
	// (GET /artists)
	GetArtists(c *fiber.Ctx, params GetArtistsParams) error
	// Create a new artist profile
	// (POST /artists)
	PostArtists(c *fiber.Ctx) error
	// Get artist by ID
	// (GET /artists/{artistId})
	GetArtistsArtistId(c *fiber.Ctx, artistId ArtistId) error
	// Update artist
	// (PUT /artists/{artistId})
	PutArtistsArtistId(c *fiber.Ctx, artistId ArtistId) error
	// Get artist's albums
	// (GET /artists/{artistId}/albums)
	GetArtistsArtistIdAlbums(c *fiber.Ctx, artistId ArtistId, params GetArtistsArtistIdAlbumsParams) error
	// Get artist's songs
	// (GET /artists/{artistId}/songs)
	GetArtistsArtistIdSongs(c *fiber.Ctx, artistId ArtistId, params GetArtistsArtistIdSongsParams) error
	// Create An admin
	// (POST /createAdmin)
	PostCreateAdmin(c *fiber.Ctx) error
	// Flag content
	// (GET /flags)
	GetFlags(c *fiber.Ctx) error
	// Flag content
	// (POST /flags)
	PostFlags(c *fiber.Ctx) error
	// Flag content
	// (POST /flags/{albumId})
	PostFlagsAlbumId(c *fiber.Ctx, albumId AlbumId) error
	// Get flagged content
	// (GET /flags/{flagsId})
	GetFlagsFlagsId(c *fiber.Ctx, flagsId FlagsId) error
	// Review a flagged content
	// (POST /flags/{flagsId}/review)
	PostFlagsFlagsIdReview(c *fiber.Ctx, flagsId FlagsId) error
	// Flag content
	// (POST /flags/{songId})
	PostFlagsSongId(c *fiber.Ctx, songId SongId) error
	// List all genres
	// (GET /genres)
	GetGenres(c *fiber.Ctx) error
	// Create a genre
	// (POST /genres)
	PostGenres(c *fiber.Ctx) error
	// Get genre by ID
	// (GET /genres/{genreId})
	GetGenresGenreId(c *fiber.Ctx, genreId GenreId) error
	// Update a genre
	// (PUT /genres/{genreId})
	PutGenresGenreId(c *fiber.Ctx, genreId GenreId) error
	// User login credentials
	// (POST /login)
	PostLogin(c *fiber.Ctx) error
	// Delete playlist
	// (DELETE /playlists/{playlistId})
	DeletePlaylistsPlaylistId(c *fiber.Ctx, playlistId PlaylistId) error
	// Get playlist by ID
	// (GET /playlists/{playlistId})
	GetPlaylistsPlaylistId(c *fiber.Ctx, playlistId PlaylistId) error
	// Update playlist
	// (PUT /playlists/{playlistId})
	PutPlaylistsPlaylistId(c *fiber.Ctx, playlistId PlaylistId) error
	// Get playlist songs
	// (GET /playlists/{playlistId}/songs)
	GetPlaylistsPlaylistIdSongs(c *fiber.Ctx, playlistId PlaylistId) error
	// Add song to playlist
	// (POST /playlists/{playlistId}/songs)
	PostPlaylistsPlaylistIdSongs(c *fiber.Ctx, playlistId PlaylistId) error
	// Remove song from playlist
	// (DELETE /playlists/{playlistId}/songs/{songId})
	DeletePlaylistsPlaylistIdSongsSongId(c *fiber.Ctx, playlistId PlaylistId, songId SongId) error
	// Purchase an album
	// (POST /purchases/albums)
	PostPurchasesAlbums(c *fiber.Ctx) error
	// Purchase a song
	// (POST /purchases/songs)
	PostPurchasesSongs(c *fiber.Ctx) error
	// Global search across all content types
	// (GET /search)
	GetSearch(c *fiber.Ctx, params GetSearchParams) error
	// Search artists with advanced filters
	// (GET /search/artists)
	GetSearchArtists(c *fiber.Ctx, params GetSearchArtistsParams) error
	// Search genres
	// (GET /search/genres)
	GetSearchGenres(c *fiber.Ctx, params GetSearchGenresParams) error
	// Search songs or albums with advanced filters
	// (GET /search/media)
	GetSearchMedia(c *fiber.Ctx, params GetSearchMediaParams) error
	// Search playlists
	// (GET /search/playlists)
	GetSearchPlaylists(c *fiber.Ctx, params GetSearchPlaylistsParams) error
	// List all songs
	// (GET /songs)
	GetSongs(c *fiber.Ctx, params GetSongsParams) error
	// Create a new song
	// (POST /songs)
	PostSongs(c *fiber.Ctx) error
	// Like a song
	// (POST /songs/like/{songId})
	PostSongsLikeSongId(c *fiber.Ctx, songId SongId) error
	// Delete song
	// (DELETE /songs/{songId})
	DeleteSongsSongId(c *fiber.Ctx, songId SongId) error
	// Get song by ID
	// (GET /songs/{songId})
	GetSongsSongId(c *fiber.Ctx, songId SongId) error
	// Update song
	// (PUT /songs/{songId})
	PutSongsSongId(c *fiber.Ctx, songId SongId) error
	// Get song contributors
	// (GET /songs/{songId}/contributors)
	GetSongsSongIdContributors(c *fiber.Ctx, songId SongId) error
	// Add contributor to song
	// (POST /songs/{songId}/contributors)
	PostSongsSongIdContributors(c *fiber.Ctx, songId SongId) error
	// Record a stream
	// (POST /streams)
	PostStreams(c *fiber.Ctx) error
	// Handle Stripe webhook
	// (POST /stripe/webhook)
	PostStripeWebhook(c *fiber.Ctx) error
	// Send tip to artist
	// (POST /tips)
	PostTips(c *fiber.Ctx) error
	// List all users
	// (GET /users)
	GetUsers(c *fiber.Ctx, params GetUsersParams) error
	// Create a new user
	// (POST /users)
	PostUsers(c *fiber.Ctx) error
	// Delete user
	// (DELETE /users/{userId})
	DeleteUsersUserId(c *fiber.Ctx, userId UserId) error
	// Get user by ID
	// (GET /users/{userId})
	GetUsersUserId(c *fiber.Ctx, userId UserId) error
	// Update user
	// (PUT /users/{userId})
	PutUsersUserId(c *fiber.Ctx, userId UserId) error
	// Get user's purchased albums
	// (GET /users/{userId}/library/albums)
	GetUsersUserIdLibraryAlbums(c *fiber.Ctx, userId UserId) error
	// Get user's purchase history
	// (GET /users/{userId}/library/purchases)
	GetUsersUserIdLibraryPurchases(c *fiber.Ctx, userId UserId, params GetUsersUserIdLibraryPurchasesParams) error
	// Get user's purchased songs
	// (GET /users/{userId}/library/songs)
	GetUsersUserIdLibrarySongs(c *fiber.Ctx, userId UserId) error
	// Get user's playlists
	// (GET /users/{userId}/playlists)
	GetUsersUserIdPlaylists(c *fiber.Ctx, userId UserId) error
	// Create a new playlist
	// (POST /users/{userId}/playlists)
	PostUsersUserIdPlaylists(c *fiber.Ctx, userId UserId) error
	// Get recently played music
	// (GET /users/{userId}/recent)
	GetUsersUserIdRecent(c *fiber.Ctx, userId UserId, params GetUsersUserIdRecentParams) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// GetAlbums operation middleware
func (siw *ServerInterfaceWrapper) GetAlbums(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAlbumsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", query, &params.Page)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter page: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "artist" -------------

	err = runtime.BindQueryParameter("form", true, false, "artist", query, &params.Artist)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter artist: %w", err).Error())
	}

	return siw.Handler.GetAlbums(c, params)
}

// PostAlbums operation middleware
func (siw *ServerInterfaceWrapper) PostAlbums(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostAlbums(c)
}

// PostAlbumsLikeAlbumId operation middleware
func (siw *ServerInterfaceWrapper) PostAlbumsLikeAlbumId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "albumId" -------------
	var albumId AlbumId

	err = runtime.BindStyledParameter("simple", false, "albumId", c.Params("albumId"), &albumId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter albumId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostAlbumsLikeAlbumId(c, albumId)
}

// DeleteAlbumsAlbumId operation middleware
func (siw *ServerInterfaceWrapper) DeleteAlbumsAlbumId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "albumId" -------------
	var albumId AlbumId

	err = runtime.BindStyledParameter("simple", false, "albumId", c.Params("albumId"), &albumId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter albumId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.DeleteAlbumsAlbumId(c, albumId)
}

// GetAlbumsAlbumId operation middleware
func (siw *ServerInterfaceWrapper) GetAlbumsAlbumId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "albumId" -------------
	var albumId AlbumId

	err = runtime.BindStyledParameter("simple", false, "albumId", c.Params("albumId"), &albumId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter albumId: %w", err).Error())
	}

	return siw.Handler.GetAlbumsAlbumId(c, albumId)
}

// PutAlbumsAlbumId operation middleware
func (siw *ServerInterfaceWrapper) PutAlbumsAlbumId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "albumId" -------------
	var albumId AlbumId

	err = runtime.BindStyledParameter("simple", false, "albumId", c.Params("albumId"), &albumId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter albumId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PutAlbumsAlbumId(c, albumId)
}

// GetAlbumsAlbumIdContributors operation middleware
func (siw *ServerInterfaceWrapper) GetAlbumsAlbumIdContributors(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "albumId" -------------
	var albumId AlbumId

	err = runtime.BindStyledParameter("simple", false, "albumId", c.Params("albumId"), &albumId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter albumId: %w", err).Error())
	}

	return siw.Handler.GetAlbumsAlbumIdContributors(c, albumId)
}

// PostAlbumsAlbumIdContributors operation middleware
func (siw *ServerInterfaceWrapper) PostAlbumsAlbumIdContributors(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "albumId" -------------
	var albumId AlbumId

	err = runtime.BindStyledParameter("simple", false, "albumId", c.Params("albumId"), &albumId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter albumId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostAlbumsAlbumIdContributors(c, albumId)
}

// GetAlbumsAlbumIdSongs operation middleware
func (siw *ServerInterfaceWrapper) GetAlbumsAlbumIdSongs(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "albumId" -------------
	var albumId AlbumId

	err = runtime.BindStyledParameter("simple", false, "albumId", c.Params("albumId"), &albumId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter albumId: %w", err).Error())
	}

	return siw.Handler.GetAlbumsAlbumIdSongs(c, albumId)
}

// GetArtists operation middleware
func (siw *ServerInterfaceWrapper) GetArtists(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetArtistsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", query, &params.Page)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter page: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "verified" -------------

	err = runtime.BindQueryParameter("form", true, false, "verified", query, &params.Verified)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter verified: %w", err).Error())
	}

	return siw.Handler.GetArtists(c, params)
}

// PostArtists operation middleware
func (siw *ServerInterfaceWrapper) PostArtists(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostArtists(c)
}

// GetArtistsArtistId operation middleware
func (siw *ServerInterfaceWrapper) GetArtistsArtistId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "artistId" -------------
	var artistId ArtistId

	err = runtime.BindStyledParameter("simple", false, "artistId", c.Params("artistId"), &artistId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter artistId: %w", err).Error())
	}

	return siw.Handler.GetArtistsArtistId(c, artistId)
}

// PutArtistsArtistId operation middleware
func (siw *ServerInterfaceWrapper) PutArtistsArtistId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "artistId" -------------
	var artistId ArtistId

	err = runtime.BindStyledParameter("simple", false, "artistId", c.Params("artistId"), &artistId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter artistId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PutArtistsArtistId(c, artistId)
}

// GetArtistsArtistIdAlbums operation middleware
func (siw *ServerInterfaceWrapper) GetArtistsArtistIdAlbums(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "artistId" -------------
	var artistId ArtistId

	err = runtime.BindStyledParameter("simple", false, "artistId", c.Params("artistId"), &artistId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter artistId: %w", err).Error())
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetArtistsArtistIdAlbumsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", query, &params.Page)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter page: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	return siw.Handler.GetArtistsArtistIdAlbums(c, artistId, params)
}

// GetArtistsArtistIdSongs operation middleware
func (siw *ServerInterfaceWrapper) GetArtistsArtistIdSongs(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "artistId" -------------
	var artistId ArtistId

	err = runtime.BindStyledParameter("simple", false, "artistId", c.Params("artistId"), &artistId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter artistId: %w", err).Error())
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetArtistsArtistIdSongsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", query, &params.Page)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter page: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	return siw.Handler.GetArtistsArtistIdSongs(c, artistId, params)
}

// PostCreateAdmin operation middleware
func (siw *ServerInterfaceWrapper) PostCreateAdmin(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostCreateAdmin(c)
}

// GetFlags operation middleware
func (siw *ServerInterfaceWrapper) GetFlags(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetFlags(c)
}

// PostFlags operation middleware
func (siw *ServerInterfaceWrapper) PostFlags(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostFlags(c)
}

// PostFlagsAlbumId operation middleware
func (siw *ServerInterfaceWrapper) PostFlagsAlbumId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "albumId" -------------
	var albumId AlbumId

	err = runtime.BindStyledParameter("simple", false, "albumId", c.Params("albumId"), &albumId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter albumId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostFlagsAlbumId(c, albumId)
}

// GetFlagsFlagsId operation middleware
func (siw *ServerInterfaceWrapper) GetFlagsFlagsId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "flagsId" -------------
	var flagsId FlagsId

	err = runtime.BindStyledParameter("simple", false, "flagsId", c.Params("flagsId"), &flagsId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter flagsId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetFlagsFlagsId(c, flagsId)
}

// PostFlagsFlagsIdReview operation middleware
func (siw *ServerInterfaceWrapper) PostFlagsFlagsIdReview(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "flagsId" -------------
	var flagsId FlagsId

	err = runtime.BindStyledParameter("simple", false, "flagsId", c.Params("flagsId"), &flagsId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter flagsId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostFlagsFlagsIdReview(c, flagsId)
}

// PostFlagsSongId operation middleware
func (siw *ServerInterfaceWrapper) PostFlagsSongId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "songId" -------------
	var songId SongId

	err = runtime.BindStyledParameter("simple", false, "songId", c.Params("songId"), &songId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter songId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostFlagsSongId(c, songId)
}

// GetGenres operation middleware
func (siw *ServerInterfaceWrapper) GetGenres(c *fiber.Ctx) error {

	return siw.Handler.GetGenres(c)
}

// PostGenres operation middleware
func (siw *ServerInterfaceWrapper) PostGenres(c *fiber.Ctx) error {

	return siw.Handler.PostGenres(c)
}

// GetGenresGenreId operation middleware
func (siw *ServerInterfaceWrapper) GetGenresGenreId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "genreId" -------------
	var genreId GenreId

	err = runtime.BindStyledParameter("simple", false, "genreId", c.Params("genreId"), &genreId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter genreId: %w", err).Error())
	}

	return siw.Handler.GetGenresGenreId(c, genreId)
}

// PutGenresGenreId operation middleware
func (siw *ServerInterfaceWrapper) PutGenresGenreId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "genreId" -------------
	var genreId GenreId

	err = runtime.BindStyledParameter("simple", false, "genreId", c.Params("genreId"), &genreId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter genreId: %w", err).Error())
	}

	return siw.Handler.PutGenresGenreId(c, genreId)
}

// PostLogin operation middleware
func (siw *ServerInterfaceWrapper) PostLogin(c *fiber.Ctx) error {

	return siw.Handler.PostLogin(c)
}

// DeletePlaylistsPlaylistId operation middleware
func (siw *ServerInterfaceWrapper) DeletePlaylistsPlaylistId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "playlistId" -------------
	var playlistId PlaylistId

	err = runtime.BindStyledParameter("simple", false, "playlistId", c.Params("playlistId"), &playlistId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter playlistId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.DeletePlaylistsPlaylistId(c, playlistId)
}

// GetPlaylistsPlaylistId operation middleware
func (siw *ServerInterfaceWrapper) GetPlaylistsPlaylistId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "playlistId" -------------
	var playlistId PlaylistId

	err = runtime.BindStyledParameter("simple", false, "playlistId", c.Params("playlistId"), &playlistId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter playlistId: %w", err).Error())
	}

	return siw.Handler.GetPlaylistsPlaylistId(c, playlistId)
}

// PutPlaylistsPlaylistId operation middleware
func (siw *ServerInterfaceWrapper) PutPlaylistsPlaylistId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "playlistId" -------------
	var playlistId PlaylistId

	err = runtime.BindStyledParameter("simple", false, "playlistId", c.Params("playlistId"), &playlistId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter playlistId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PutPlaylistsPlaylistId(c, playlistId)
}

// GetPlaylistsPlaylistIdSongs operation middleware
func (siw *ServerInterfaceWrapper) GetPlaylistsPlaylistIdSongs(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "playlistId" -------------
	var playlistId PlaylistId

	err = runtime.BindStyledParameter("simple", false, "playlistId", c.Params("playlistId"), &playlistId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter playlistId: %w", err).Error())
	}

	return siw.Handler.GetPlaylistsPlaylistIdSongs(c, playlistId)
}

// PostPlaylistsPlaylistIdSongs operation middleware
func (siw *ServerInterfaceWrapper) PostPlaylistsPlaylistIdSongs(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "playlistId" -------------
	var playlistId PlaylistId

	err = runtime.BindStyledParameter("simple", false, "playlistId", c.Params("playlistId"), &playlistId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter playlistId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostPlaylistsPlaylistIdSongs(c, playlistId)
}

// DeletePlaylistsPlaylistIdSongsSongId operation middleware
func (siw *ServerInterfaceWrapper) DeletePlaylistsPlaylistIdSongsSongId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "playlistId" -------------
	var playlistId PlaylistId

	err = runtime.BindStyledParameter("simple", false, "playlistId", c.Params("playlistId"), &playlistId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter playlistId: %w", err).Error())
	}

	// ------------- Path parameter "songId" -------------
	var songId SongId

	err = runtime.BindStyledParameter("simple", false, "songId", c.Params("songId"), &songId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter songId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.DeletePlaylistsPlaylistIdSongsSongId(c, playlistId, songId)
}

// PostPurchasesAlbums operation middleware
func (siw *ServerInterfaceWrapper) PostPurchasesAlbums(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostPurchasesAlbums(c)
}

// PostPurchasesSongs operation middleware
func (siw *ServerInterfaceWrapper) PostPurchasesSongs(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostPurchasesSongs(c)
}

// GetSearch operation middleware
func (siw *ServerInterfaceWrapper) GetSearch(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSearchParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "query" -------------

	if paramValue := c.Query("query"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument query is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "query", query, &params.Query)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter query: %w", err).Error())
	}

	// ------------- Optional query parameter "types" -------------

	err = runtime.BindQueryParameter("form", true, false, "types", query, &params.Types)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter types: %w", err).Error())
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", query, &params.Page)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter page: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	return siw.Handler.GetSearch(c, params)
}

// GetSearchArtists operation middleware
func (siw *ServerInterfaceWrapper) GetSearchArtists(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSearchArtistsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "query" -------------

	err = runtime.BindQueryParameter("form", true, false, "query", query, &params.Query)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter query: %w", err).Error())
	}

	// ------------- Optional query parameter "genre" -------------

	err = runtime.BindQueryParameter("form", true, false, "genre", query, &params.Genre)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter genre: %w", err).Error())
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", query, &params.Sort)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter sort: %w", err).Error())
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", query, &params.Page)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter page: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	return siw.Handler.GetSearchArtists(c, params)
}

// GetSearchGenres operation middleware
func (siw *ServerInterfaceWrapper) GetSearchGenres(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSearchGenresParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "query" -------------

	err = runtime.BindQueryParameter("form", true, false, "query", query, &params.Query)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter query: %w", err).Error())
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", query, &params.Sort)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter sort: %w", err).Error())
	}

	return siw.Handler.GetSearchGenres(c, params)
}

// GetSearchMedia operation middleware
func (siw *ServerInterfaceWrapper) GetSearchMedia(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSearchMediaParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "query" -------------

	err = runtime.BindQueryParameter("form", true, false, "query", query, &params.Query)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter query: %w", err).Error())
	}

	// ------------- Optional query parameter "artist" -------------

	err = runtime.BindQueryParameter("form", true, false, "artist", query, &params.Artist)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter artist: %w", err).Error())
	}

	// ------------- Optional query parameter "genre" -------------

	err = runtime.BindQueryParameter("form", true, false, "genre", query, &params.Genre)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter genre: %w", err).Error())
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", query, &params.Sort)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter sort: %w", err).Error())
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameter("form", true, false, "order", query, &params.Order)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter order: %w", err).Error())
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", query, &params.Page)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter page: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	return siw.Handler.GetSearchMedia(c, params)
}

// GetSearchPlaylists operation middleware
func (siw *ServerInterfaceWrapper) GetSearchPlaylists(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSearchPlaylistsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "query" -------------

	err = runtime.BindQueryParameter("form", true, false, "query", query, &params.Query)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter query: %w", err).Error())
	}

	// ------------- Optional query parameter "owner" -------------

	err = runtime.BindQueryParameter("form", true, false, "owner", query, &params.Owner)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter owner: %w", err).Error())
	}

	// ------------- Optional query parameter "isPublic" -------------

	err = runtime.BindQueryParameter("form", true, false, "isPublic", query, &params.IsPublic)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter isPublic: %w", err).Error())
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", query, &params.Sort)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter sort: %w", err).Error())
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", query, &params.Page)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter page: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	return siw.Handler.GetSearchPlaylists(c, params)
}

// GetSongs operation middleware
func (siw *ServerInterfaceWrapper) GetSongs(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSongsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", query, &params.Page)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter page: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "genre" -------------

	err = runtime.BindQueryParameter("form", true, false, "genre", query, &params.Genre)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter genre: %w", err).Error())
	}

	// ------------- Optional query parameter "artist" -------------

	err = runtime.BindQueryParameter("form", true, false, "artist", query, &params.Artist)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter artist: %w", err).Error())
	}

	// ------------- Optional query parameter "album" -------------

	err = runtime.BindQueryParameter("form", true, false, "album", query, &params.Album)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter album: %w", err).Error())
	}

	return siw.Handler.GetSongs(c, params)
}

// PostSongs operation middleware
func (siw *ServerInterfaceWrapper) PostSongs(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostSongs(c)
}

// PostSongsLikeSongId operation middleware
func (siw *ServerInterfaceWrapper) PostSongsLikeSongId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "songId" -------------
	var songId SongId

	err = runtime.BindStyledParameter("simple", false, "songId", c.Params("songId"), &songId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter songId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostSongsLikeSongId(c, songId)
}

// DeleteSongsSongId operation middleware
func (siw *ServerInterfaceWrapper) DeleteSongsSongId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "songId" -------------
	var songId SongId

	err = runtime.BindStyledParameter("simple", false, "songId", c.Params("songId"), &songId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter songId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.DeleteSongsSongId(c, songId)
}

// GetSongsSongId operation middleware
func (siw *ServerInterfaceWrapper) GetSongsSongId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "songId" -------------
	var songId SongId

	err = runtime.BindStyledParameter("simple", false, "songId", c.Params("songId"), &songId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter songId: %w", err).Error())
	}

	return siw.Handler.GetSongsSongId(c, songId)
}

// PutSongsSongId operation middleware
func (siw *ServerInterfaceWrapper) PutSongsSongId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "songId" -------------
	var songId SongId

	err = runtime.BindStyledParameter("simple", false, "songId", c.Params("songId"), &songId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter songId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PutSongsSongId(c, songId)
}

// GetSongsSongIdContributors operation middleware
func (siw *ServerInterfaceWrapper) GetSongsSongIdContributors(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "songId" -------------
	var songId SongId

	err = runtime.BindStyledParameter("simple", false, "songId", c.Params("songId"), &songId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter songId: %w", err).Error())
	}

	return siw.Handler.GetSongsSongIdContributors(c, songId)
}

// PostSongsSongIdContributors operation middleware
func (siw *ServerInterfaceWrapper) PostSongsSongIdContributors(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "songId" -------------
	var songId SongId

	err = runtime.BindStyledParameter("simple", false, "songId", c.Params("songId"), &songId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter songId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostSongsSongIdContributors(c, songId)
}

// PostStreams operation middleware
func (siw *ServerInterfaceWrapper) PostStreams(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostStreams(c)
}

// PostStripeWebhook operation middleware
func (siw *ServerInterfaceWrapper) PostStripeWebhook(c *fiber.Ctx) error {

	return siw.Handler.PostStripeWebhook(c)
}

// PostTips operation middleware
func (siw *ServerInterfaceWrapper) PostTips(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostTips(c)
}

// GetUsers operation middleware
func (siw *ServerInterfaceWrapper) GetUsers(c *fiber.Ctx) error {

	var err error

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsersParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", query, &params.Page)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter page: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	return siw.Handler.GetUsers(c, params)
}

// PostUsers operation middleware
func (siw *ServerInterfaceWrapper) PostUsers(c *fiber.Ctx) error {

	return siw.Handler.PostUsers(c)
}

// DeleteUsersUserId operation middleware
func (siw *ServerInterfaceWrapper) DeleteUsersUserId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameter("simple", false, "userId", c.Params("userId"), &userId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter userId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.DeleteUsersUserId(c, userId)
}

// GetUsersUserId operation middleware
func (siw *ServerInterfaceWrapper) GetUsersUserId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameter("simple", false, "userId", c.Params("userId"), &userId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter userId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetUsersUserId(c, userId)
}

// PutUsersUserId operation middleware
func (siw *ServerInterfaceWrapper) PutUsersUserId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameter("simple", false, "userId", c.Params("userId"), &userId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter userId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PutUsersUserId(c, userId)
}

// GetUsersUserIdLibraryAlbums operation middleware
func (siw *ServerInterfaceWrapper) GetUsersUserIdLibraryAlbums(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameter("simple", false, "userId", c.Params("userId"), &userId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter userId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetUsersUserIdLibraryAlbums(c, userId)
}

// GetUsersUserIdLibraryPurchases operation middleware
func (siw *ServerInterfaceWrapper) GetUsersUserIdLibraryPurchases(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameter("simple", false, "userId", c.Params("userId"), &userId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter userId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsersUserIdLibraryPurchasesParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", query, &params.Page)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter page: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	return siw.Handler.GetUsersUserIdLibraryPurchases(c, userId, params)
}

// GetUsersUserIdLibrarySongs operation middleware
func (siw *ServerInterfaceWrapper) GetUsersUserIdLibrarySongs(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameter("simple", false, "userId", c.Params("userId"), &userId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter userId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetUsersUserIdLibrarySongs(c, userId)
}

// GetUsersUserIdPlaylists operation middleware
func (siw *ServerInterfaceWrapper) GetUsersUserIdPlaylists(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameter("simple", false, "userId", c.Params("userId"), &userId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter userId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetUsersUserIdPlaylists(c, userId)
}

// PostUsersUserIdPlaylists operation middleware
func (siw *ServerInterfaceWrapper) PostUsersUserIdPlaylists(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameter("simple", false, "userId", c.Params("userId"), &userId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter userId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostUsersUserIdPlaylists(c, userId)
}

// GetUsersUserIdRecent operation middleware
func (siw *ServerInterfaceWrapper) GetUsersUserIdRecent(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameter("simple", false, "userId", c.Params("userId"), &userId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter userId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsersUserIdRecentParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", query, &params.Page)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter page: %w", err).Error())
	}

	return siw.Handler.GetUsersUserIdRecent(c, userId, params)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(m)
	}

	router.Get(options.BaseURL+"/albums", wrapper.GetAlbums)

	router.Post(options.BaseURL+"/albums", wrapper.PostAlbums)

	router.Post(options.BaseURL+"/albums/like/:albumId", wrapper.PostAlbumsLikeAlbumId)

	router.Delete(options.BaseURL+"/albums/:albumId", wrapper.DeleteAlbumsAlbumId)

	router.Get(options.BaseURL+"/albums/:albumId", wrapper.GetAlbumsAlbumId)

	router.Put(options.BaseURL+"/albums/:albumId", wrapper.PutAlbumsAlbumId)

	router.Get(options.BaseURL+"/albums/:albumId/contributors", wrapper.GetAlbumsAlbumIdContributors)

	router.Post(options.BaseURL+"/albums/:albumId/contributors", wrapper.PostAlbumsAlbumIdContributors)

	router.Get(options.BaseURL+"/albums/:albumId/songs", wrapper.GetAlbumsAlbumIdSongs)

	router.Get(options.BaseURL+"/artists", wrapper.GetArtists)

	router.Post(options.BaseURL+"/artists", wrapper.PostArtists)

	router.Get(options.BaseURL+"/artists/:artistId", wrapper.GetArtistsArtistId)

	router.Put(options.BaseURL+"/artists/:artistId", wrapper.PutArtistsArtistId)

	router.Get(options.BaseURL+"/artists/:artistId/albums", wrapper.GetArtistsArtistIdAlbums)

	router.Get(options.BaseURL+"/artists/:artistId/songs", wrapper.GetArtistsArtistIdSongs)

	router.Post(options.BaseURL+"/createAdmin", wrapper.PostCreateAdmin)

	router.Get(options.BaseURL+"/flags", wrapper.GetFlags)

	router.Post(options.BaseURL+"/flags", wrapper.PostFlags)

	router.Post(options.BaseURL+"/flags/:albumId", wrapper.PostFlagsAlbumId)

	router.Get(options.BaseURL+"/flags/:flagsId", wrapper.GetFlagsFlagsId)

	router.Post(options.BaseURL+"/flags/:flagsId/review", wrapper.PostFlagsFlagsIdReview)

	router.Post(options.BaseURL+"/flags/:songId", wrapper.PostFlagsSongId)

	router.Get(options.BaseURL+"/genres", wrapper.GetGenres)

	router.Post(options.BaseURL+"/genres", wrapper.PostGenres)

	router.Get(options.BaseURL+"/genres/:genreId", wrapper.GetGenresGenreId)

	router.Put(options.BaseURL+"/genres/:genreId", wrapper.PutGenresGenreId)

	router.Post(options.BaseURL+"/login", wrapper.PostLogin)

	router.Delete(options.BaseURL+"/playlists/:playlistId", wrapper.DeletePlaylistsPlaylistId)

	router.Get(options.BaseURL+"/playlists/:playlistId", wrapper.GetPlaylistsPlaylistId)

	router.Put(options.BaseURL+"/playlists/:playlistId", wrapper.PutPlaylistsPlaylistId)

	router.Get(options.BaseURL+"/playlists/:playlistId/songs", wrapper.GetPlaylistsPlaylistIdSongs)

	router.Post(options.BaseURL+"/playlists/:playlistId/songs", wrapper.PostPlaylistsPlaylistIdSongs)

	router.Delete(options.BaseURL+"/playlists/:playlistId/songs/:songId", wrapper.DeletePlaylistsPlaylistIdSongsSongId)

	router.Post(options.BaseURL+"/purchases/albums", wrapper.PostPurchasesAlbums)

	router.Post(options.BaseURL+"/purchases/songs", wrapper.PostPurchasesSongs)

	router.Get(options.BaseURL+"/search", wrapper.GetSearch)

	router.Get(options.BaseURL+"/search/artists", wrapper.GetSearchArtists)

	router.Get(options.BaseURL+"/search/genres", wrapper.GetSearchGenres)

	router.Get(options.BaseURL+"/search/media", wrapper.GetSearchMedia)

	router.Get(options.BaseURL+"/search/playlists", wrapper.GetSearchPlaylists)

	router.Get(options.BaseURL+"/songs", wrapper.GetSongs)

	router.Post(options.BaseURL+"/songs", wrapper.PostSongs)

	router.Post(options.BaseURL+"/songs/like/:songId", wrapper.PostSongsLikeSongId)

	router.Delete(options.BaseURL+"/songs/:songId", wrapper.DeleteSongsSongId)

	router.Get(options.BaseURL+"/songs/:songId", wrapper.GetSongsSongId)

	router.Put(options.BaseURL+"/songs/:songId", wrapper.PutSongsSongId)

	router.Get(options.BaseURL+"/songs/:songId/contributors", wrapper.GetSongsSongIdContributors)

	router.Post(options.BaseURL+"/songs/:songId/contributors", wrapper.PostSongsSongIdContributors)

	router.Post(options.BaseURL+"/streams", wrapper.PostStreams)

	router.Post(options.BaseURL+"/stripe/webhook", wrapper.PostStripeWebhook)

	router.Post(options.BaseURL+"/tips", wrapper.PostTips)

	router.Get(options.BaseURL+"/users", wrapper.GetUsers)

	router.Post(options.BaseURL+"/users", wrapper.PostUsers)

	router.Delete(options.BaseURL+"/users/:userId", wrapper.DeleteUsersUserId)

	router.Get(options.BaseURL+"/users/:userId", wrapper.GetUsersUserId)

	router.Put(options.BaseURL+"/users/:userId", wrapper.PutUsersUserId)

	router.Get(options.BaseURL+"/users/:userId/library/albums", wrapper.GetUsersUserIdLibraryAlbums)

	router.Get(options.BaseURL+"/users/:userId/library/purchases", wrapper.GetUsersUserIdLibraryPurchases)

	router.Get(options.BaseURL+"/users/:userId/library/songs", wrapper.GetUsersUserIdLibrarySongs)

	router.Get(options.BaseURL+"/users/:userId/playlists", wrapper.GetUsersUserIdPlaylists)

	router.Post(options.BaseURL+"/users/:userId/playlists", wrapper.PostUsersUserIdPlaylists)

	router.Get(options.BaseURL+"/users/:userId/recent", wrapper.GetUsersUserIdRecent)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xda2/bOJf+K4R2gZnBKvEl6UzrT5um2759kZkNmhYvdgdFwUi0zakkakgqqTfIf1/w",
	"IomSqJstx3Kbb4lMUhTPcx4e8hwePjgeCWMSoYgzZ/HgxJDCEHFE5X8wuE3C977400fMozjmmETOwnn/",
	"BpAl4GsEZBHHdbB4HEO+dlwngiFyFllt16Ho7wRT5DsLThPkOsxboxCKZpeEhpA7CydJsCjJN7GoyjjF",
	"0cp5fHQdSDlmvKUTskxNL9L6u3VjGcAVa+6FKGLvQ1p5ty6sUERRcxdkEXsf0tq79SHAIebVHvyRhLeI",
	"il5gjkIGYkRBDFdZV/5OEN3kfVGtmG/20RImAXcW86nrhPAbDpPQWcym06wTOOJohajshWy60olruEIg",
	"LWZ/se6T5b0z+4sCuAla4ZeWsg+80cZuY89ItGruiChh74Suu1sHEoZocwdECXsHdN1dOvCYFpbcdCGJ",
	"R1AWJTGiHCNFWQZdtDToOh65Q/R9CFfoEw1EDfQNhnEgCq05j9liMvH86DRMGPZgHJ96JJxIVmOT2XQ2",
	"kdVP/4rFmOfvotj6KoogR/4FL3TMhxydcBwiOTDQ/+8o2KQDU2miMOhmXy9JECBPPBdyIAkFt4hxiQZm",
	"6wu2jk7r+zH7IohshWT1muK3hAQIRo7kiq9KJjVFI0kaomRMsYcK3/Tq9NUrY1CXAYHcqaqo6HWAIENv",
	"IC824Myn87OT6exkPjWlYw545QM55kGplXdSbIyDf2BuHcsk9neT66OpEn/qPhjT3uesBrn9C3lcvPRC",
	"zXc14P9Dapz5FR/XCHwg3lfwGkb+ntC5JahCEvF1sLnCjKNImx1Zx2fzF1MxBdS0YsBgZzGY7NbKG3eI",
	"4iVWepB1VjXbrhb3MAgQfw0DGJVALz739IUF9m3fX8JQxrUGHmwwuiQRp/g24YTuTKS6JUyij/JHE35L",
	"BHki+rYf5FGygQHfXCPqoYhr0yAf1BedeGRoPTbMzsrg2GTxX5TapOARv/g559NzW/d9xCEOWFXtRZ8Q",
	"48iX0wG4hwxEhIMlSexMECLGykPofECMJNRDTVVL3y87njdn++S3wl6ufrECxBfIbXz+28l8+nE2X0yn",
	"i+n0f+uYve9UWjRn3sixRD5A3+IARjCdWA0b3xxjzNTQJgwxkEQw4WtC8f+JEZeFGFhSEoJwA+4J/Vo/",
	"Hxc7cZFwcrISlChGAyQR/jtBAPso4oJ6aKETs/kZOn/x628n6OWr25PZ3D87gecvfj05n//66+x89tv5",
	"dFqYBbuSM0WQ2UboEnK0InSTjsodJoEcpkKvPBJvKF6t+Rfz9xB+u0LRiq+L5r350phQjugXQWNfcKu9",
	"CVQFHK3kI6FtKOJDjE+la4xDnrDCusGJUeRjaXaXxiihFEUcqDpl/ETCdv3TqEzRHUb3kiN9zELMmPwb",
	"SrMOSTMg/568WtWGgXSFeMuwaTMuHSvwswQwoWo1/8texk53jOvZodg1QYuic2mHbpEQZ2pt5uOlFzhq",
	"06EwJPqXOvusjU5e7EAnJear4NcUSnEcMg3LoGXjyXdyUV8hytrlgCwPvDWk0ONIUdHtBoifpdUCcMQ4",
	"TUK55zPg8qDfOkruR7AJJd7XjkuoqGLXCpu2dSaS1YraaRvl63QRb5mD+68S00U/m8ynI1op3oglIXgP",
	"AnKHACcgkGY34GTQZeJ1chtgr/DmJQyY1Rq2rLl+34C38I5QzBG4qVvDPqXBX2deq75bwZRQbw2ZRWs9",
	"OS14m+Inf7p5M6AEYrgRyn2TzVbmnCz+4HZbPNa9vq4sx2dzczWe77FVDdG0jcNKpvglbj7q5cGxCU9g",
	"zrIeyvfCW+e6XmsnVZh9ETwl3yS3UMUf1TlUPYCUwo2smviYdCcluSE0+e3lq4mseBrGZ134aAv6y9/0",
	"1MyXUFhj1etfAI4AQx6JfGbaOfOz32xwNvbcWwU5um21YEOxZ0eSmJ/YJUkibtlw6bTjEiuLdRtM6Kod",
	"8VfdHJydzgfZHHxxMnuxy+bgxT1iJFST1EH2BsvkYeDfIAfX8P3EmhDNkbFx4CeGLLsRt5iUpmohYGlN",
	"ULXK/QPdg/+pWeYOoN4ohLiEt7/IOvpP/a/AmSlQVdzSzhJT2z7pP8k6GlSz843asiXUQc+hrYtviBWd",
	"MWTsnlC/dWyKNV3nXphZeUdEU2sSIeXQK7b2H7P5mVgJvnw1tespWeIA9ZwpxJTNJrP52UTX7zhXDGT/",
	"VdcUYsy++LZRLmljjiFDVkarbga/DAeGnKpK9+g6DHkJxXxz462RNgZeI0gRvUj4Wiqg/O9t+rn//NfH",
	"1JspwSN/zTsuBl35zXC0JJY9puv3YEkoCGEEV2LBLSWjNgGYq/xHrtxjYS6AkQ9Ss4qdZtbvwrmk8D4A",
	"F9fvHbkxzlTbs9Pp6VSMMolRBGPsLJwz+ciVjkH5bdqXJv5cISlIQTaSv8SU67xD/EKVcAuBCX8+OP9O",
	"0dJZOP82ycMXJnmRifTzPrqt5ZQjWhQsjsxbHHBE5apZSg68f1PjUc5CD7r7MT8LHLGYREyJeD6dqmWm",
	"2rgStmYcB9iTAzH5S+/A5e1vuUMMOayxaotWp23ItN91opyuFUv00TKD7LKRXNaM8pLWuZArV0CWGqxK",
	"e5IwhHTjLJwr8SMMgvRX1+FwJYDjaDx9FnxFmAVz14TloNOb56+Jv+kloQ5DWGQTTb0lWMwOC4uuX/Lk",
	"whfvBdqaEG87VwpULPUa+qnzo8Ctkj5MVv3zs9DIHDyXsmEAQYTus/CmCn4e3ZS+JsIgnzzo9eGjHMwW",
	"aF3hr+gii47qR23pOvTANPK0IhcDBmCkxSFFfl4VubDDjTf1knrhDYL4JeM3ib0gcR8FSC0yijJ/I5+r",
	"6nuQ+Pl3K3Gl5GpYtZKfVSX+ltBb7Pso6idsJZV65XZb7JEj192j4/rUu12n+KpUSfMzab9DvE2tXSdO",
	"bIydDCrwgxoTzwBrAJheTQ7NM59ks52MiGw2mXh5VE6HpZFG5qVZ6fuhpcvSWHRapJhhTYdfqlzphUpB",
	"rHUE5RXFuMWqZXg8DM9aBQGNeyHkFUPkun/VU8PMeDuAvr+PhdGF75sABZz0ZDYVkNyV0lLX7/fCZTfp",
	"13ciMelTGA97yS/4iemY8h3tsKydCnCU8zUDkHJuNCJGFzncBmEaC6wDvWq2CbOIYXOjsLznPy7MZq6L",
	"bjuDqviotgY1Nur2BjPoZCDUT1rm2azeXix6PY4j3x/MwNHpW54cA2rT/om2CNXLtPvKCieDzCYPqff2",
	"sQOvXeSe3p7TYFpxpJwyZti07jaoYo3TnCpS2W8wCaZuw2FYyR+WoZ6h1gy1Pe87pL7JrozUxSFbhOeW",
	"/tkcpO7Qptr4+O6qlx01Eg/rVcGI+olljtZdSTFvqopLV5/qrcVn+wqyCM8t15DP6DySVWmKqJZlaQ9s",
	"VhamGTTNlamyLC/8EEfN/t5Lo+D203FRbn2ioy1DOaY5+zCwCSH31jhaqXQZbCvb/yICUEs1g4r8XwFE",
	"ZvxoIqq3ssCI2CDrcScikGc3D08EakspKB9o6ydR8S3GscFUnL8TX8usZUMgF+UQ2l06u9NwJrPmiF3H",
	"aHVVODusXXPAriUgOX1hobmsj5+34p/Zd8s/l/p0YxruP/i+RBckZ+zUNWRJwvs5WqmHnMXwGtFKA0iw",
	"MrVMHnROqcfWSeZtlnyqn+jSpFWjslmPdpbaaYayNdAJHBN10qaDgmuUfFDld8PKENNgftR+q7Pyz5Zw",
	"IyKVmLcDo64L+yFSJSDrMtXcpKnK+kFQZzj7AScalfZt6GlGr40aZpd3qsSIZoe8z52mB5VYYUwuS3NB",
	"WvVYrtIBT+WlJdC8PDHENLwzQA/huH0BqzSBRpcveXrjQGbrSF2Vj1Y/Y5rXsyR416Kxkwd92vOxXXff",
	"5edCe3Ftep50VKbhEUi5zbOoSjXtU8qPrPgVTR6ocSsOKfBnGhkrwDJ/4qPNHdiNRgKyatvVvpJFhjL1",
	"s0Pd7ee2zWPOWensYdt2Vdps0yHcUSOQk6/IvvWX6PP6TdCUZ/qfHpk3iechxpZJABS0JPvNBuMOlTnR",
	"8uJPRi4+F+DoDgbYFzOtTKIHg7KdJcZHdbFQyDCPE74WTz1zLy3P9PSQZ3rucCYszTfFrs380D2jGPOq",
	"P9ThsHTI9nw+zMjrnUIgk1rjKbH9y/ZwHBQbedKa1DLLp/b0jGPAo9neygo2mVzpB1esriIW6gyvvWBh",
	"eAvMENeop8Bjgt9+o7ta2Kl+bmqPorFgdrtImrGSWM/g9pGFvUj5ARzlEBiG4MqxLyWCq10O7A8ug3gS",
	"smsz+iUT1PWendiWJAvyhBngpITAoU+bybTE5lu2o7qC96G3VS6hvKVTwgS0u4ML4/z7hhNFIblDvkoh",
	"V4TUcNPmB/kShaniixpQlSa8MiKjG3gwLb1zAqHtU4/q9Ka/I74mvqozfHpVaESDFF83frYsmZNGot5G",
	"czItdwBzUr8a5Ll7Byfb7B1Z1IqhEymqKzqR2ZEdVCI1CIbRCAvKS7TCKY4R0OVAKAvq5Vslq39XA2EA",
	"zWH5PPKsON+V4qSXr9WpDUOQeuumVdeNKlGxMUrIlqUARzSsOWuc/lt/01plMCsXfJAwhCcMiZ5w5Gf+",
	"6fR+BtEAE5aZ+ip1gQRzdeZIfXDDzWwyV7kmf6npsGzNfi2fY2vYBofv+aAGRUwOxn6SN2ZJhHc+6+0O",
	"FICR37vYvalrw2ost8YGyLzgOpxwGHyQoigm1T+fW2/kqqZ3fWLLWqkm1T0urfsDcguDVH2hRwljMsak",
	"oOEGnWlyMrmsS34GVa02S0MttYGf9RFaQRG/tBBdD2LL8zYoT7poCRBan981dZn2eMcNoRwsMQp88HNM",
	"4iSAYipxg/SKO7fpmxihNTejOnlb5g1C5sPsFWl7n5+Z0ng+BMNJFjBgMCaNr5xvsmfA0GqmfwT3mK8B",
	"9O9g5IkluFSQNs1vDw5UtbIAg+56n+vlgGpfo5J7U8Q65RvnHvhuulI7iR+VqlgjLzUwK3GXNpUIkY9h",
	"u0b8Lov1UQiZZ13MUeo6j71MhsZk2zgbWrKdj3nK1bdcfPEhR256NcZeFN58U/EajvIlUS0fQahfe3t5",
	"+puti6Ipo3NQ/icf/mg2QKaIx+jay/hI+fhg5Nsz3GuGUKXSixu3m8sLa61m8sq3x/sQWOZfzJjMKLwX",
	"OiP3EaIgvYmjkWxk0W3fE8uL7iYxxXeQo+YMcNm1eI0Z4LoyW35LrpvfcLkXZjPu4y3cptnMbM9LjF02",
	"LI7Kcsr5w0pRscEZdhpqi0bZMpZgsAyPymwZ0lzZ6XqZPq3LfJz1jWtPT33bY1I8doz5U/OjXTpFjf1k",
	"VznyJs010xR1s6tHrX30xu2BYvqazg7f4R4iqOFpsk+WvE5mkiIV+6Jup+l0/FZWvsJf0fMR3J430+gj",
	"uHu7l6ZdzN1DnHaJZ/phI5T2e9CgRrpus0l01Fp6XFzedpDApuGFGFsZdVY+QGDM8jWHBwaT8yFNhLEn",
	"gT0ksPZ7RKDzrNH50hkDkDtdMTJGEvJ+mMtmJBvV3DXTeekxNAqe75l5vmem7p6ZJiLjFMG2yOwbXWio",
	"+FOPJBGnm0st8xB+u0LRSnzM3BI16qM77KE01aLlmvDrPE1XtjWr7wmv3gv+fJ5l2GlYQgNQ5BG6Fzh/",
	"kC2LNZx8kwlj+UD0NIMyjtHkHt2uCfnaimgco3/povZZtPgBuixYw8gPKjki/iGfAh03fZ+1WxfOynHc",
	"onMfRYnBjkCEQuMKoF8GRLkhKkDK8nd3Cek2wLXFYYqSjsH81gbd4+OP9OY4tizYVFIHmw/LdTiFEVPZ",
	"+OoG7dBejI84BgxFHLAsO0WwGV73b1DkA45jeVda+TYGqSBKm+Qd+0129yeG6N59IGMyxsWI9EpNr7Kb",
	"jGjDX8l04IVd5jFIWNGzrwDSbLanINqHra2Ty4ybyY4xfY7MStPbl2B3FsjPrGImY6DJgzqo1GEXWdb9",
	"lB5r6kdL+jTUD7WLLMW4313kGum6zZPK4DI87JwxZi1u20WWhbb0E71DXAKgsslsTAw1m8yDweCQs8oz",
	"6upQt98t5s5TyiTAtxTSTYc7xgxAXqlKW14zNkaSGubQ3sF2ltNzv37hQrDhYJXy2E+s+qocZhoWzUDL",
	"Dqr3w1q+07Et3L7r+MfCqHaLdMyOgI8OxU8BX7DGjBMZd9cLvq1xkVXobhcpOUaWZMd8WXpOXMa9dHum",
	"yHIEYSPEOoX8G/BqiPs/QmwNebj8cBjLo673hy5L6HbXnHDDo+fQOS9nzzkvO+S8fJqo1w6pu0qUR5Gn",
	"5daB7z6owvuz//JDB50MxbHm/z2mybmK0L6sqCAUbCT6kA/ChMnjXJW1r2yY3tmPxgXEg8GaSOwmNHAW",
	"zprzeDGZZD8sXk5fzqXQdcsP6YENfYJM4EY/udIZH8xnWfKC/IlM7//4+fH/AwAA//+5iN2b77kAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
